### PR TITLE
fix: Slate editor props

### PR DESCRIPTION
**Pull request by zbeyens**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Bug

 TS2322: Type 'Editor' is not assignable to type 'ReactEditor'.

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
@zbeyens can you give me a code sample of how you're using this?

**Comment by zbeyens** [comment]
I'm using this helper function to create an editor with an array of plugins. The output type is `Editor` and `Slate` currently only accepts `ReactEditor`.

```js
export const useCreateEditor = (
  editorPlugins: PluginEditor[] = [],
  plugins: SlatePlugin[] = []
) =>
  useMemo(() => {
    let editor = createEditor();

    const newEditorPlugins = createEditorPlugins(editorPlugins, plugins);

    newEditorPlugins.forEach(plugin => {
      editor = plugin(editor);
    });

    return editor;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
```

**Comment by zbeyens** [comment]
A simpler example everyone is using:

```js
const editor = useMemo(() => withHistory(withReact(createEditor())), []);
``` 
`editor` type is `HistoryEditor`

Typescript error:

> Property 'insertData' is missing in type 'HistoryEditor' but required in type 'ReactEditor'.

**Comment by ianstormtaylor** [comment]
Dang. I think we need to figure out a way to have the plugins return an editor with the proper fields instead of loosening the expectation. Because a `ReactEditor` needs `insertData`. And a `HistoryEditor` needs `undo`, `redo` and `history`.

**Comment by zbeyens** [comment]
Why not just setting the type to `Editor`? All examples are working well on my end with this change.

`[key: string]: any;` allows new fields anyways.

**Comment by ianstormtaylor** [comment]
@zbeyens because then there's no type safety on those extra pieces? That doesn't sound good to me. Shouldn't the plugins be using `Editor & {...}` to instead denote that they've added extra stuff?

**Comment by zbeyens** [comment]
True!

What about generic types for all plugins?

`export declare const withReact: <T>(editor: T) => T & ReactEditor;`
`export declare const withHistory: <T>(editor: T) => T & HistoryEditor;`

Works well on my end

**Comment by ianstormtaylor** [comment]
Beautiful, thank you @zbeyens!

**Pull request merged**
