### PR TITLE
Splitting Before a Void Inline Block Adds a Duplicate

### PR DESCRIPTION
**Pull request by kellyjosephprice**
Related Issue: #612

### CODE REVIEW

**Comment by kellyjosephprice** [comment]
I'm still unfamiliar with the code base, so I wanted to start with small changes to confirm I'm moving in the right direction.

**Comment by ianstormtaylor** [comment]
Hey @kellyjosephprice this is awesome!

Could you add a test for splitting block nodes as well? Since it looks like this will apply to both cases. Thank you!

**Comment by tobiasandersen** [comment]
Hey, I just tried this out. It does indeed fix the issue with duplicated inline nodes, but it also introduces some new problems:

1. When splitting on an inline node, the inline node moves down, but the cursor stays.
2. Performing `undo` in this state breaks the editor.

The problem with undo arrises when joining the two nodes, specifically on [this line](https://github.com/ianstormtaylor/slate/blob/master/src/models/node.js#L1398). The reason it breaks is that the first node this time is a `Text` node (which doesn't have the `nodes` property). (The bug we're trying to solve here is actually masking this issue, since the first node in that case will be of kind `Inline`.) What's interesting to me is that joining the two blocks using backspace works just fine. 

I'm also completely unfamiliar with the code base (although I've been using Draft extensively for some time), but I'll see if I can track it down even further.

**Comment by ianstormtaylor** [comment]
This is fixed now!

**Pull request closed without merging**
