### PR TITLE
Development Guide for iOS

### PR DESCRIPTION
**Pull request by thesunny**
Created the development guide for iOS.

### CODE REVIEW

**Comment by thesunny** [comment]
This should complete 1 task in the roadmap https://github.com/ianstormtaylor/slate/issues/1720

**Comment by ianstormtaylor** [comment]
Hey @thesunny, there are a _lot_ of changes here. Two things:

First, I'm a little concerned about having so much iOS-specific content that isn't really related to Slate at all, and it going to add to the maintenance burden. I can see how this would be helpful to people developing iOS, but in my opinion it doesn't really belong in the Slate codebase because it's not something that Slate developers should be maintaining. Instead of merging it here, can you host it as a separate repo that we can just link to from the Slate docs instead?

Second, can you explain all of the other types of changes? From what I can see there are multiple different things going on...

  - Renaming files to remove `/index.md` endings?
  - Rewriting paths to remove leading `./`?
  - Splitting `utils` out into individual files?
  - ...

**Comment by SamyPesse** [comment]
@ianstormtaylor most of the changes are caused by GitBook, it looks like @thesunny used GitBook to write these changes with a GitHub sync setup to its fork.

When GitBook exports changes to a GitHub repository, it normalizes the structure and the markdown.

**Comment by ianstormtaylor** [comment]
@SamyPesse Ah gotcha, thanks for the clarification. Unfortunately it seems like although some of the changes are not harmful, some lose information. From what I can see the harmful ones are:

1. [It removes links from images.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-fd6ba6f1d5f8de5a1eecc59a018798a9R34)
2. [It changes some links (can't tell which/when) to reference the repository of the contributor instead of the canonical repository.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-c70719328a0d4f9d0e5b680142bddbe3R89)
3. [It removes `<kbd>` formatting.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-42420b0f8e11149ba3e244e8ac8bb6caR7)
4. [It reformats HTML content.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-ec07648e3f81fda8ce5441976e425d81R241)
5. [It misplaces reformatted HTML content.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-222d47dedeaabd19ad12e29d7f6e6b75R3) 

And then the non-desirable ones are:

1. [It escapes all instances of `(` and `)` in regular prose.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-1e6d4ba97394b236e2edafe8ad137150R159)
1. [It re-hosts images in `.gitbook/assets` even if they were already inside the repository.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-fd6ba6f1d5f8de5a1eecc59a018798a9R34)
2. [It creates duplicates of images with numbered prefixes like `slack (1).png`.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-c70719328a0d4f9d0e5b680142bddbe3R89)
3. [It changes `#docs` links to include the file name, like `Introduction.md#docs`.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-d3fb80366cfc18143c65a4b54d284e23R5)
4. [It messes with table formatting, which is set by Prettier.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-3927f629241aeb4295ea3c3df12162d1R9)
5. [It changes relative links to remove leading `./`.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-784e12de76b21f32d379fa3353d73fe3R7)
6. [It changes the heading levels.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-d3fb80366cfc18143c65a4b54d284e23R9)
7. [It changes `html` formatted code blocks to be `markup`.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-62d5a271963d7ab55f8fb86e855c0704R71)
8. [It changes `js` formatted code blocks to be `javascript`.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-f215d28549a0115b90249f071bf82f5bR86)
9. [It adds `text` syntax to unlabeled code blocks.](https://github.com/ianstormtaylor/slate/pull/1723/files#diff-f215d28549a0115b90249f071bf82f5bR152)

---

With all of that @thesunny unfortunately I can't merge this PR with these kinds of changes, it's just too much changed, some bad and some good. But if you extract the iOS guide to be hosted elsewhere, we can add a link to it in the contributing documentation.

**Comment by thesunny** [comment]
I redid the commit here: https://github.com/ianstormtaylor/slate/pull/1732

Closing this PR

**Pull request closed without merging**
