### PR TITLE
Add tests for plugins

### PR DESCRIPTION
**Pull request by mxstbr**
I set out to provide a failing test for some weird behaviour I'm seeing with a custom plugin I'm writing where the `rules` of a plugin schema are not ran. This is JSFiddle reproducing the issue: https://jsfiddle.net/8y30hx90/ (note how the `alert()` is never called)

For some reason the tests passes, so I guess I'm doing something wrong? Time to quadruplecheck... Anyways, at least you now have a first test for plugins!

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Awesome! Thank you @mxstbr 😄

**Comment by mxstbr** [comment]
I still don't understand why the JSFiddle doesn't work though: https://jsfiddle.net/8y30hx90/ (note how the alert() is never called)

Any ideas?

**Comment by ianstormtaylor** [comment]
@mxstbr if I update it to have a decorator function that matches anything then it seems to work: https://jsfiddle.net/8y30hx90/1/ — I think just matches without other parts of the rule will never be called because they don't do anything?

**Comment by mxstbr** [comment]
I'm so bad, it turns out it didn't work because I accidentally typo'ed `rule.decorator` rather than `rule.decorate` and didn't notice until copy and pasting your working code. Ugh, thanks for helping me resolve that!

**Pull request merged**
