### PR TITLE
feat(react-slate): Ability to add multiple placeholders.

### PR DESCRIPTION
**Pull request by xobotyi**
**Description**
As for my case i had a need to add multiple placeholders for a single editable, that are hidden separately as content fills.

**Example**

Above example has such `placeholder` property:
```ts
placeholder={[
  'Summarize your issue.',
  <>
    And describe it in details here.
    <br />
    Try to avoid using languages not supported by interface, it will significantly improve
    and speed up our work.
  </>,
]}
```

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [x] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
@xobotyi can you see if your use case would be solved by https://github.com/ianstormtaylor/slate/pull/4190 with fragment rendering? It seems like a simpler solution so I'd rather go with it if possible.

**Comment by xobotyi** [comment]
@ianstormtaylor current placeholder will disappead at the moment first character entered. Thus no, it cant be achieved with renderer.

**Comment by ianstormtaylor** [comment]
@xobotyi I believe your case could instead be solved by handling the placeholder logic at the block level? One for the heading and one for the paragraph like with the Forced Layout example?

**Comment by xobotyi** [comment]
@ianstormtaylor and no again, at block level i wont be able to gain access to keypress handlers to move between placholders by pressing enter.
Currently if you press Enter and there is empty placeholder ahead, it will switch to that line instead of splitting current one. I dont know how to manage it outside the slate.

**Comment by ianstormtaylor** [comment]
@xobotyi I'm not sure I understand what you mean by splitting the block. But since placeholders internally are implemented with decorations, I believe you could implement a similar behavior in userland with special decoration logic for your two nodes.

**Comment by xobotyi** [comment]
@ianstormtaylor when enter pressed - handler calls `Transforms.splitNodes` which splits current line in two (i did not told about block splitting).
If such question was only about decoration i wold not change the base components, here it is also about behaviour

**Review by dylans — CHANGES_REQUESTED** [review]
@xobotyi unfortunately this one has fallen a bit behind main.

If you're still interested in landing this, please update against the latest and then I'll review. Apologies that this PR was ignored after your last comment.

**Comment by dylans** [comment]
Closing this one out due to inactivity and it being stale. Feel free to reopen or create a new PR if I missed something here. Thanks!

**Pull request closed without merging**
