### PR TITLE
docs: convert examples to typescript

### PR DESCRIPTION
**Pull request by wendellhu95**
ts-slate

#### Is this adding or improving a _feature_ or fixing a _bug_?

Not relevant.

#### What's the new behavior?

Convert all example files to TypeScript and update next.js to 9.4.0.

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #3713
Reviewers: @CameronAckermanSEL

### CODE REVIEW

**Comment by wendellhu95** [comment]
It seems that `exportPathMap` breaks in production mode after updating to Next.js 9.4.0. I am working on that.

**Comment by wendellhu95** [comment]
Ping @CameronAckermanSEL.

**Comment by dustinsenos** [comment]
Curious why you’re converting, rather than not just adding TypeScript docs?

**Comment by CameronAckermanSEL** [comment]
Thank you _so_ much for doing all of this work. I'm sorry this took so long for me to get to.

**Comment by wendellhu95** [comment]
> Curious why you’re converting, rather than not just adding TypeScript docs?

I saw this converting things days ago in the issue list. :P

**Pull request merged**
