### PR TITLE
Copy void

### PR DESCRIPTION
**Pull request by ianstormtaylor**
Hey @oyeanuj thank you so much for your work in #676! 

I realized that it was going to require a lot more digging and rethinking how copy/cut worked, so I pulled in your changes and went from there.

### CODE REVIEW

**Comment by oyeanuj** [comment]
This is awesome, and far more complicated than I had imagined! Thanks!

**Comment by oyeanuj** [comment]
@ianstormtaylor Btw, I tried it on the Images example page and getting the following error after trying to copy-paste the image within the editor.
```
Uncaught TypeError: Cannot read property 'split' of null
    at onPasteText (http://slatejs.org/build.prod.js:15967:14)
    at Object.onPaste (http://slatejs.org/build.prod.js:15934:16)
```

**Comment by ianstormtaylor** [comment]
@oyeanuj shit you're right. Weirdly if you click the image again and then copy it it seems to work. I'll investigate!

**Comment by ianstormtaylor** [comment]
@oyeanuj fix incoming!

**Pull request merged**
