### PR TITLE
refactor: use vitest instead of mocha

### PR DESCRIPTION
**Pull request by JonasKruckenberg**
**Description**
After chatting with @horacioh about slate testing I went ahead and converted the unit testing for all 4 packaged from mocha to vitest. Contrary to #4928 I used a script to actually rewrite and group up all the test files to a more "standard" approach using `describe` and `test`. While the speedup gained by vitest isn't significant on it's own (On my m1 macbook pro it was ~3.6s using vitest vs 4.8s using mocha) the live-retesting features offered by vitest make actually writing tests much nicer.
Vitest can detect changes in source-code and automatically re-run only affected tests for example. So during actual development and test writing to comparison is more like 200ms using vitest vs 4.8s using mocha on my machine.

The other advantage vitest brings to the table is testing without building. This means that tests can be run against the source-code, something that vitest actively encourages. This also tilts the scale in vitests favor as CI test runs can forego the build step. (I didn't touch the actual workflow files yet, though)

**Issue**
N/A

**Example**
N/A

**Context**
This PR was born out of prior with #4928 and my need to have variations of existing tests (i.e. multiple tests per file) for #4378.

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

### CODE REVIEW

**Comment by dylans** [comment]
As a quick note, I'm following along but haven't said much yet. Testing is a challenge to get right. My perspective is mostly aligned with the comments in https://github.com/ianstormtaylor/slate/pull/4903#issuecomment-1076373954 and I'm just sort of waiting to see what emerges from the various PRs and trying to avoid my own bias.

**Review by TheSpyder — CHANGES_REQUESTED** [review]
While I appreciate that a lot of work probably went into this, deleting the `index.js` files in favour of repeating boilerplate everywhere doesn't seem like a good change to me. I don't think the existing approach is particularly non-standard, both `describe` and `it` were used before, it's just a choice to use file convention over more detailed configuration.

Likewise, while using aliases to redirect import statements to the source code avoids the seemingly annoying bundle step, what we have was a very deliberate choice too. Mocha can be used this way too with the right configuration; running tests run on the bundled output is just something the original authors (and I) believe is important. With rollup watch mode the slowest part of testing is actually babel, not bundling.

As for your comments about not needing to build in CI, I very strongly disagree. CI should test that everything is ready to release not take shortcuts just to get faster feedback.

**Comment by joshuawootonn** [comment]
Hey @JonasKruckenberg 👋🏼 

I am currently trying to use vitest to test a slate plugin I am creating. I am getting this error: 

CleanShot 2023-03-13 at 13 34 57@2x

whenever any of the actions I am running use `Transforms.XXXX`. I have the same tests working with jest. Did you happen to run into anything like this / do you have any input as to how to resolve it?

**Comment by dylans** [comment]
I think the consensus that emerged has been to use Playwright for E2E tests, and testing-library + mocha for unit tests.

This has mostly meant not using Vite/vitest or Cypress. Closing this out for now in favor of what we've been using in main.

**Pull request closed without merging**
