### PR TITLE
Add/render to iframe

### PR DESCRIPTION
**Pull request by vleletko**
As discussed in #215 , added support for Slate IFrame rendering, but in quite different way. 

There is actually no need to pass `dom={...}` becasue valid window could be deducted by the `event.native.target` transparently. 

One more problem found in React `SelectionEventPlugin`: it also has hardcoded `window` references.
Basicly version of `SelectionEventPlugin` swallowing all onSelection events, and this leads to incosistent slection state in slate.

To handle this I created small project [react-frame-aware-selection-plugin](https://github.com/vleletko/react-frame-aware-selection-plugin)

It is used in provided example.

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
@vleletko very cool! I like how minimal the changes are.

Question for you: can you open a pull request on React with the injector functionality proposed? I'm a little wary of having to use the `injector`, and would love to see that logic added natively to React if they agree with it.

**Comment by ianstormtaylor** [comment]
Hey @vleletko also, I've just added the ability to "scroll to the cursor when a change is made" in `0.10.11`, but I think this logic may also need to be reconsidered for iframes? Can you take a look and see what you think? Thanks!

**Comment by vleletko** [comment]
@ianstormtaylor, checked code related to "scroll to the cursor when a change is made", and yes, to support iframes it should be changed. 

Problem in [element-scroll-to](https://github.com/webmodules/element-scroll-to) code. 
It references to `window` and to `document.body`. 
Opened issue [#2](https://github.com/webmodules/element-scroll-to/issues/2)

About custom injector - I'll open issue in react repo, but I think they will not change it, at least [react-tap-event-plugin](https://github.com/zilverline/react-tap-event-plugin) still exists. 

btw, injector is used only in examples. We can remove Frame example from slate, and maybe make separate repo for it.

**Comment by ianstormtaylor** [comment]
Added in `0.11.2`, thanks so much @vleletko for the help on this!

Updated the example to render with Bootstrap buttons and typography based on the rich text example. If you run into any issues while using it for your live preview let me know.

**Comment by vleletko** [comment]
@ianstormtaylor, Thanks for great project!!

**Comment by entiendoNull** [comment]
This may be the wrong place to ask, but I have been looking through documentation and also read through this post (that caught my attention to begin with): https://github.com/ianstormtaylor/slate/issues/215

My hope is to create a small page builder. The template included lives within an iframe so that I can isolate for example styling from my builder. I am doing this in React and my initial hope was using React-Quill as my rich text editor... but I stumbled over the exact same issue: Quill was instantiated in the parent document and text selection (- and surely other events too) were lost due to this.

I am certainly willing to perform tests my self, but still am eager to find out more about what this turned out like. I read somewhere that the `react-frame-aware-selection-plugin` is not maintained as much as it should... so was this functionality added directly to Slate? Or was interest lost somewhere along the way? Is there a straight forward way to achieve this?

Thanks for your time.
Your project looks amazing.

**Pull request merged**
