### PR TITLE
Allow HTMLSerializer to deserialize an empty doc

### PR DESCRIPTION
**Pull request by conorcussell**
Thanks to @vpontis for doing the actual work, I noticed that all we need to close this PR https://github.com/ianstormtaylor/slate/pull/742  and this issue https://github.com/ianstormtaylor/slate/issues/539 was a test case to cover deserialising an empty string. Let me know if this looks ok?

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Hey @conorcussell thanks! Is there any reason we can use the existing test fixtures setup? (Instead of creating another test case with `it(` with custom logic?)

**Comment by conorcussell** [comment]
I'm sure i thought there was a reason i couldnt use them at the time, but looking again now it will work fine with the normal fixtures setup. Will fix! Thanks

**Comment by conorcussell** [comment]
Hey @ianstormtaylor changed it to use the fixtures now! Thanks

**Comment by ianstormtaylor** [comment]
Thanks @conorcussell!

**Pull request merged**
