### PR TITLE
add Chinese translate to `v0.57.1`

### PR DESCRIPTION
**Pull request by loveloki**
#### add Chinese translate to `v0.57.1`
the docs's  Chinese translate is to old(based on `v0.24.1` )
so add a new to instead it

### CODE REVIEW

**Comment by loveloki** [comment]
I just started learning to use pull requests.
If i have any questions, please let me know.
：)

**Comment by Jay0328** [comment]
There is a [template](https://github.com/ianstormtaylor/slate/blob/master/.github/PULL_REQUEST_TEMPLATE.md) for pull requests.

**Comment by loveloki** [comment]
> There is a [template](https://github.com/ianstormtaylor/slate/blob/master/.github/PULL_REQUEST_TEMPLATE.md) for pull requests.

Yes, it will appear automatically when I write，thank you.

**Comment by Mookiepiece** [comment]
@loveloki I think those changes are already committed on #3393 
by the way, [Introduction.md](https://github.com/ianstormtaylor/slate/blob/master/docs/Introduction.md) this page also has a link need to be updated

**Pull request closed without merging**
