### PR TITLE
fix for deleting across an inline

### PR DESCRIPTION
**Pull request by tyler-johnson**
Noticed an issue with Slate deleting around an inline node, where the selection start and end are in text nodes. This test shows the issue. I will attempt a bug fix next week.

### CODE REVIEW

**Comment by tyler-johnson** [comment]
I added a fix for it, however now the tests are failing due to a missing `jsdom` dependency. Looks like https://github.com/ianstormtaylor/slate/pull/364/commits/f6b39b7c194b6958212194dc3f7fbbae9ac5f0e0 may need to be merged before these will pass.

**Comment by ianstormtaylor** [comment]
Hey @tyler-johnson can you rebase/merge against `master` on this? Looks like the `jsdom` dep in `package.json` is conflicting. If so I can merge!

**Comment by SamyPesse** [comment]
@ianstormtaylor I've merged #393 in #396

**Comment by tyler-johnson** [comment]
Merged with master. Thanks!

**Comment by ianstormtaylor** [comment]
@SamyPesse ah should I wait for that then and not merge this one?

**Comment by SamyPesse** [comment]
@ianstormtaylor If you want to ship a release before, then merge it; We'll rebase and squash our PR once it's ready.

**Comment by SamyPesse** [comment]
@ianstormtaylor tests are working, except the benchmark on node v4 (not related to this PR): https://travis-ci.org/ianstormtaylor/slate/builds/170874832

**Comment by ianstormtaylor** [comment]
@SamyPesse ah do the benchmarks never work on Node 4? (I missed that caveat.)

**Comment by SamyPesse** [comment]
No it works, the build failed with `No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.`

It was too slow for Travis

**Comment by ianstormtaylor** [comment]
Oh yeah sorry, I meant do the benchmarks never work in Node 4 on Travis? Should I just turn off Node 4 for Travis in that case then?

**Comment by SamyPesse** [comment]
Everything should work fine on Node v4, but build time may vary and since the benchmarks are slow, [Travis can kill them](https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out) (it can happen on Node v6 as well).

You can merge it, and if it happens again, I'll make a PR to integrate a solution to print something while running.

**Comment by ianstormtaylor** [comment]
Okay sounds good, thanks!

**Pull request merged**
