### PR TITLE
Add className to placeholder

### PR DESCRIPTION
**Pull request by lcswillems**
#### Have you checked that...?

- [ ] The new code matches the existing patterns and styles.
- [ ] The tests pass with `yarn test`.
- [ ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ ] The relevant examples still work. (Run examples with `yarn start`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #
Reviewers: @

### CODE REVIEW

**Comment by CameronAckermanSEL** [comment]
Thanks for the PR. I think the general approach makes sense but I'm feeling that maybe this is a bit too constricting and instead there should be a prop or something that allows the user to pass in their own class name. But then I'm also worried about what the surface area of that API would look like. I'll post back some ideas if I have some, but this might be something that Ian needs to look at since it's changing the API.

**Comment by lcswillems** [comment]
Okay, I understand. @ianstormtaylor What would be the best solution here? Using a classname or properties?

**Comment by delijah** [comment]
Why do you want to pass a `className`? You could also just pass your own component and style it the way you want it... like `<Editable placeholder={<Placeholder>{placeholder}</Placeholder>} />`.

**Comment by ianstormtaylor** [comment]
Hey @lcswillems thanks for working on this. I agree with @CameronAckermanSEL that it feels like we should provide a more customizable version of this idea. I wrote up a solution in https://github.com/ianstormtaylor/slate/issues/4123 that I think would work, if any one wants to contribute! Thanks.

**Pull request closed without merging**
