### PR TITLE
Deduplicate dirty paths for normalization.

### PR DESCRIPTION
**Pull request by themithy**
Hi,

Paths accumulated for normalization are not deduplicated which leads to poor performance in case we wait with flushing for some reasons.

Thanks.

### CODE REVIEW

**Comment by kierson** [comment]
I would like to add that without this deduplication, applying a lot of operations at once is ultra slow.

**Comment by rikkit** [comment]
I think this code would read better by using lodash - already a dependency

```js
this.tmp.dirty = _.uniqBy(dirty, path => path.join(","));
```

**Comment by Calyhre** [comment]
This deduplication fix so much of our performance issues too. Applying a fair amount of operations is non-linear on time spent normalizing dirty paths.

**Comment by Calyhre** [comment]
Combine it with #2959 for even faster operations

**Comment by ianstormtaylor** [comment]
Thank you @themithy! This is great.

**Pull request merged**
