### PR TITLE
fix: extend forward / backward

### PR DESCRIPTION
**Pull request by ericedem**
#### Is this adding or improving a _feature_ or fixing a _bug_?

_bug_

#### What's the new behavior?

Fix behavior for <kbd>shift + left</kbd> and <kbd>shift + right</kbd>. Now they will correctly move forward / backward.

#### How does this change work?

turns out that the hotkey `'left'` would also pick up with a modifier key `'shift+left'` so checking for `Hotkeys.isExtendForward()` needs to come before `Hotkeys.isMoveForward()` and it needs to short circuit with `return true`. Likewise for backward.

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x] The relevant examples still work. (Run examples with `yarn watch`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #2307 
Reviewers: @ianstormtaylor

### CODE REVIEW

**Comment by ericedem** [comment]
It does seem strange that `'shift+left'` would get picked up by the hotkey looking for `'left'`. I would think that should only happen if it were `'shift?+left'` but I could be missing something here.

**Comment by skogsmaskin** [comment]
I think it the order as you have done here in this PR is the right one (most complex combination tested first). Isn't it just that a test for 'left' would also be true when pressing shift-left?

But I'm curious about why you had to return true and not just the change like before?

**Comment by ericedem** [comment]
@skogsmaskin The problem is that if it doesn't match the void / empty check, then no change will be returned and the onKeyDown handler will continue checking hotkeys. Eventually it reaches the `moveForward()` and `moveBackward()` handlers which still match the <kbd>shift</kbd> modified arrow key.

I think the root cause is that the unmodified hotkey should not match the <kbd>shift</kbd> modified hotkey. Filed an issue with `is-hotkey` here: https://github.com/ianstormtaylor/is-hotkey/issues/11

**Comment by skogsmaskin** [comment]
Oh, so it's the other way around? Shift-left evals true for *only* left too? That must be a bug.
Maybe something [here](https://github.com/ianstormtaylor/is-hotkey/blob/master/src/index.js#L151) that doesn't take non-character keys into account. I suggest we fix the root-cause (is-hotkey) first, then solve this without the workaround.

**Comment by ianstormtaylor** [comment]
Thanks for tracking that down @ericedem and @skogsmaskin! With `0.1.4` of `is-hotkey` I believe this should be fixed, so maybe we can just bump instead of reordering now?

**Comment by ericedem** [comment]
> maybe we can just bump instead of reordering now?

Works for me! Looking at upgrading, we seem to have two different dependencies on `is-hotkey`, one as a dev dependency at the root level 0.1.1, and one in slate-hotkeys at 0.1.3. Not super familiar with yarn, trying to sort through that now.

**Comment by skogsmaskin** [comment]
Just bump both, I think the package.json one is for the examples.

**Comment by ericedem** [comment]
I manually modified both package.json files to `^0.1.4` and ran `yarn install`. Fixed the bug for me locally.

**Comment by ianstormtaylor** [comment]
Thanks @ericedem and @skogsmaskin, this is great!

**Comment by dannsam** [comment]
Awesome work @ericedem @skogsmaskin!

**Pull request merged**
