### PR TITLE
Fix move_node dirtyPath and PathUtils.transform calculations

### PR DESCRIPTION
**Pull request by jtadmor**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Fixing a _bug_

#### What's the new behavior?

`getDirtyPaths` does a better job of handling some `move_node` operation edge cases.

`PathUtils.transform` also does a better job of handling a `move_node` operation edge case where the `path` we are transforming is the path that was moved.

Lastly, the `element.moveNode` itself also uses the same logic to determine where to actually insert the node, ensuring that it is being put in the correct place in the hierarchy.

#### How does this change work?

Previously there was code to handle certain cases, prefaced by a `// HACK` comment.

This generalizes the previous approach by running all ancestors of `path` and `newPath` through `PathUtils.transform` to get the true new path that results after the move operation, rather than potentially non-existent (or incorrect) paths.

A test is added that confirms the correct behavior for the edge case discovered (where `newPath` is the parent of `path`).

While doing research, I also discovered that `PathUtils.transform` did not use the correct check for `move_node` in a few specific cases.

Critically, the only real edge case is when the path being transformed is either the `operation.path` or a descendant of it. In that case, the only circumstance where we aren't simply moving the path to its new location is when the `operation.path` is a left-sibling of an ancestor of the `operation.newPath`.

Thus, a new check is added for `isYounger(path, newPath) && path.size < newPath.size`, not `isBefore(path, newPath)`.

The rest of the logic for that method is simplified by simply running it through the two actions that make a move: the removal of the node at one path and the insertion of that node at the new path.

Tests were added to confirm this behavior is correct, you can see the sample paths I used in those tests (I had to draw out some trees on paper).

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #2521, #2574
Reviewers: @

### CODE REVIEW

**Comment by jtadmor** [comment]
Not 100% sure the last test I added (`delete/all-with-nested-blocks`) is correct, but it does not error out.

**Comment by ianstormtaylor** [comment]
Hey @jtadmor thanks for tackling this.

It's hard for me to tell exactly what these changes are doing, and whether or not they introduce any new bugs. What exact cases are broken? And why the need to switch the way the logic works in places to do more convoluted things with operations?

**Comment by bebbi** [comment]
@ianstormtaylor 

> What exact cases are broken?

#2521, #2574, #2604 with #2605.

It would be helpful to understand what to contribute beyond those.

> It's hard for me to tell exactly what these changes are doing

Would more inline comments and/or more high level context in the pull solve this?

> whether or not they introduce any new bugs

I'll try to qualify this PR from our experience: When working with highly nested trees, slate was unusable to our client due to lots of `Uncaught Error: Node.assertNode could not find node with path or key: List [...]` occurring on both undo and paste. Yes, they suspended our project because of this.

Since merging this they haven't encountered a single error so far. It's one of the most important stability fixes I have seen in slate.
Formally, I'd think addressing all current tests plus the new issues' tests appears to answer this. Do you feel there's a gap of tests around core functionality here that needs to be addressed?

Side-note: the reason #2605 is a separate PR with only tests in it is that while it belongs to another pull #2589, I couldn't add those tests to #2589 because before this fix here they would just error out with the same error above - so #2605 tests depends on both this fix and #2589.

**Comment by jtadmor** [comment]
Hi ian,

Thanks for taking a look.

I know some of the tests are a bit hard to read and immediately understand what was broken. It's also a bit harder to understand because several different things were broken.

1. `getDirtyPaths` not picking up all paths on `move_node` operations, depending on how `path` and `newPath` related.
- Test:  Jump to `with-plugin-normalization.js`)
- Code: Jump to `editor/getDirtyPaths`

2. For multi-op commands including `move_node`, previous dirty paths were not being transformed correctly. During normalization, this would throw errors.
- Tests: User facing bug: `delete/all-with-nested-blocks`.
- Code: `PathUtils.transform`.

3. When inverting a `move_node` op, the inverted paths were not always correctly calculated. This would throw errors during undo.
- Tests: `undo/insert-fragment` for the user facing bug.
- Code: `invert/invertOperation`.

4. `element.moveNode` was not always accurate, and would sometimes move a node to the wrong place. This was also breaking when trying to undo certain operations.
- Tests: `undo/insert-fragment` for user facing bug.
- Code: `element/moveNode`


What I determined reading through the code is that there were many different places where we were trying to deal with various cases in `move_node`. By re-using `PathUtils.transform` (which was written after a lot of the other code), we can handle these cases more consistently. I also added a variety of tests (and fixes) to `PathUtils.transform` to ensure we were capturing the correct behavior for some of the trickier cases (see `from-before-not-younger`, `from-before-younger`, `siblings-backward`, `siblings-forward`).

The alternative is to copy all the logic from `PathUtils.transform` into `getDirtyPaths`, `moveNode`, `invertOperation`. My view was that this made the code harder to read and understand, and harder to maintain going forward. It seems that simply deferring to `PathUtils.transform` is more self-documenting: what we want is a reference to where a node in the tree is based on what its path was before a `move_node` op.

**Comment by ianstormtaylor** [comment]
@jtadmor thanks, that's very helpful. I agree with you now about having it more self-documenting by reusing `PathUtils.transform`. Thank you!

@bebbi that makes total sense. Once I merge this you can merge those two PRs into one it sounds like. Thank you!

**Pull request merged**
