### PR TITLE
Update wrapNodes to use lowest mode and create passing test.

### PR DESCRIPTION
**Pull request by BrentFarese**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Fixing a bug.

#### What's the new behavior?

Slate's `wrapNodes` function does not handle nested block structures with inlines.  When trying to have an inline wrap other nodes (e.g., other inlines or text), if the Slate document has a nested block structure, wrapNodes inserts the wrapping inline in the incorrect place.

This is a result of `wrapNodes` using `mode: 'highest'` [here](https://github.com/ianstormtaylor/slate/blob/1d7ab974292a3e831908a2ba0aab9fdd8a66fe10/packages/slate/src/transforms/node.ts#L798).

#### How does this change work?

By switching to `mode: 'lowest'`, we get the correct `roots` for inline wrapping with nested block documents.

This PR changes to `mode: 'lowest'` and also adds a test with a nested block structure in place of `packages/slate/test/transforms/wrapNodes/inline/inline-across.js` (now re-named to `inline-across-nested.js`).

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

#### Does this fix any issues or need any specific reviewers?

Reviewers: @CameronAckermanSEL, @timbuckley, @ianstormtaylor

### CODE REVIEW

**Comment by BrentFarese** [comment]
@CameronAckermanSEL know you have been deep in the release, but give this a look when you can and then I can merge it if you don't have any comments.  Thanks!

**Comment by CameronAckermanSEL** [comment]
Hi @BrentFarese , I'm really sorry that I'm leaving you hanging here. I will try to look at this PR this weekend. Thank you again for the contribution, it is greatly appreciated.

One thing though is that I'm deliberately withholding merging of PRs until release. The release is currently containing a great deal of bug fixes, and at this time I have a good confidence that we are not releasing any new bugs. I'd like to release what we have now, and then get in some other high value bug fixes out in a more controlled way shortly after.

Thanks for your patience and understanding :)

**Comment by BrentFarese** [comment]
No problem at all @CameronAckermanSEL thanks for taking a look when you can!

**Comment by CameronAckermanSEL** [comment]
Hey @BrentFarese , finally in a position to look at this and merge it. Thank you! I see that we modified an existing test , would it be redundant to have the old test case left alone and have a new file for deeply nested inlines?

**Comment by BrentFarese** [comment]
No problem @CameronAckermanSEL!  Added back the test you referred to.  Also added .idea to .gitignore as that is the IDE I'm using.  Good to squash and merge?

**Comment by CameronAckermanSEL** [comment]
This looks good! But I don't know why the netlify deployment is failing. I'm not too concerned about it yet, but just for safety could you merge/rebase with master explicitly and see if that clears the problem?

Thanks, @BrentFarese !

**Comment by BrentFarese** [comment]
K just rebased off Master @CameronAckermanSEL and that seems to have done the trick.

**Pull request merged**
