### PR TITLE
Remove warning in getFragmentAtRange for node (#652)

### PR DESCRIPTION
**Pull request by Rebulus**

### CODE REVIEW

**Comment by Rebulus** [comment]
@ianstormtaylor, Sorry, I didn't find a good place for testing it. Could you help me to recognize it?

**Comment by ianstormtaylor** [comment]
@Rebulus that looks good, I don't think that piece has tests for it right now. It looks like there's a type for `starNode` can you fix that and I can merge? Thanks!

**Comment by Rebulus** [comment]
@ianstormtaylor cool, thank you 😄  I fixed the typo.

**Comment by ianstormtaylor** [comment]
Awesome, thanks @Rebulus!

**Pull request merged**
