### PR TITLE
Refactor duplicate code in mixin

### PR DESCRIPTION
**Pull request by zhujinxuan**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Refactor

#### What's the new behavior?
Eliminate some duplication of `mixin(create())`

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x] The relevant examples still work. (Run examples with `yarn watch`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #
Reviewers: @

### CODE REVIEW

**Comment by thesunny** [comment]
Looks good to me.

**Comment by ianstormtaylor** [comment]
Hey guys, what is the reason for doing this? It doesn't strike me as necessary at all, and it just makes this harder to read...

This seems unnecessary...

**Comment by zhujinxuan** [comment]
@ianstormtaylor I feel like repeatedly typing 
```
mixnin(create(objName), [obj])
```
is a bit duplicate, and easy to make mistake (like typo) when refactor code.

I think it is perhaps better to make the same patterns combined together.  Feel free to revert this PR if you think it is not necessary.

**Comment by ianstormtaylor** [comment]
@zhujinxuan I understand what you're saying, but in practice that kind of logic leads to refactoring things that don't need to be refactored, and in ways that make the code harder to read. 

The pull requested code here is harder to understand than the original. The duplication in this case wasn't actually causing any harm. I'll revert it when I get the time.

In the future, please don't merge PR's like this.

**Comment by thesunny** [comment]
@ianstormtaylor Sorry, that's my bad especially since I agree with you.

**Pull request merged**
