### PR TITLE
feat: add a basic mention implementation example

### PR DESCRIPTION
**Pull request by ericedem**
Just a simple example to get people started with their own mentions implementation.

#### Is this adding or improving a _feature_ or fixing a _bug_?

_example_

#### What's the new behavior?

kapture 2018-10-16 at 17 13 39

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x] The relevant examples still work. (Run examples with `yarn watch`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #
Reviewers: @

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Hey @ericedem this is awesome! Thank you! Would you be willing to update it to use a floating portal like the hover menu does? I think it would make it more compelling for people that way.

**Comment by ericedem** [comment]
@ianstormtaylor My intent was to create something as simple as possible since it is already a fairly complicated topic. Though thinking about it again, a lot of the complexity in our app comes from making it accessible (keyboard) and containing it within a plugin. Here it might be possible to do it in a simple way, I'll look into it 🤔

**Comment by ericedem** [comment]
@ianstormtaylor Ok I updated the example to use a floating anchored menu, and updated to 0.42. Cheers 🍻

**Comment by ianstormtaylor** [comment]
Thank you @ericedem this is awesome!

**Pull request merged**
