### PR TITLE
Update after.js

### PR DESCRIPTION
**Pull request by baijiahei**
#### Is this adding or improving a _feature_ or fixing a _bug_?
bug

#### Have you checked that...?

- [ ] The new code matches the existing patterns and styles.
- [ ] The tests pass with `yarn test`.
- [ ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ ] The relevant examples still work. (Run examples with `yarn start`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #
Reviewers: @

### CODE REVIEW

**Comment by CameronAckermanSEL** [comment]
Hi @baijiahei , could you explain a little bit more about what this PR is looking to achieve so I know what I should be looking at and testing?

Thanks!

**Comment by baijiahei** [comment]
> Hi @baijiahei , could you explain a little bit more about what this PR is looking to achieve so I know what I should be looking at and testing?
> 
> Thanks!

slate v0.47 can't input text on Safari unless i add this code

**Comment by CameronAckermanSEL** [comment]
Hi @baijiahei , if we merge in this PR it won't impact the 0.47 version because it is out of support. Do the currently hosted slate examples work on safari?

**Comment by baijiahei** [comment]
@CameronAckermanSEL No, some wired behaviors when i input chinese

Mar-16-2020 15-59-32
1.when i input  '发多少' , focus where lose and go to text 'bold', then i input '发送到', the focus will jump forward a word, then i can't input anything, and an error occur
2.english seem alright

**Comment by baijiahei** [comment]
×
@CameronAckermanSEL 
Error info:
Error: Cannot resolve a DOM point from Slate point: {"path":[1,0],"offset":79}
toDOMPoint
./src/plugin/react-editor.ts:251
  248 | }
  249 | 
  250 | if (!domPoint) {
> 251 |   throw new Error(
      | ^  252 |     `Cannot resolve a DOM point from Slate point: ${JSON.stringify(point)}`
  253 |   )
  254 | }
View compiled
toDOMRange
./src/plugin/react-editor.ts:265
  262 | 
  263 | toDOMRange(editor: ReactEditor, range: Range): DOMRange {
  264 |   const { anchor, focus } = range
> 265 |   const domAnchor = ReactEditor.toDOMPoint(editor, anchor)
      | ^  266 |   const domFocus = Range.isCollapsed(range)
  267 |     ? domAnchor
  268 |     : ReactEditor.toDOMPoint(editor, focus)
View compiled
(anonymous function)
./src/components/editable.tsx:148
  145 |   return
  146 | }
  147 | 
> 148 | const newDomRange = selection && ReactEditor.toDOMRange(editor, selection)
      | ^  149 | 
  150 | // If the DOM selection is already correct, we're done.
  151 | if (
View compiled
▼ 16 stack frames were expanded.
commitHookEffectList
.node_modules/react-dom/cjs/react-dom.development.js:22030
commitLifeCycles
.node_modules/react-dom/cjs/react-dom.development.js:22080
commitLayoutEffects
.node_modules/react-dom/cjs/react-dom.development.js:25344
callCallback
.node_modules/react-dom/cjs/react-dom.development.js:336
invokeGuardedCallbackDev
.node_modules/react-dom/cjs/react-dom.development.js:385
invokeGuardedCallback
.node_modules/react-dom/cjs/react-dom.development.js:440
commitRootImpl
.node_modules/react-dom/cjs/react-dom.development.js:25082
unstable_runWithPriority
.node_modules/scheduler/cjs/scheduler.development.js:697
commitRoot
.node_modules/react-dom/cjs/react-dom.development.js:24922
finishSyncRender
.node_modules/react-dom/cjs/react-dom.development.js:24329
performSyncWorkOnRoot
.node_modules/react-dom/cjs/react-dom.development.js:24307
(anonymous function)
.node_modules/react-dom/cjs/react-dom.development.js:12199
unstable_runWithPriority
.node_modules/scheduler/cjs/scheduler.development.js:697
flushSyncCallbackQueueImpl
.node_modules/react-dom/cjs/react-dom.development.js:12194
flushSyncCallbackQueue
.node_modules/react-dom/cjs/react-dom.development.js:12182
batchedUpdates$1
.node_modules/react-dom/cjs/react-dom.development.js:24392
▲ 16 stack frames were expanded.
(anonymous function)
./src/plugin/with-react.ts:91
  88 | // children and selection can get out of sync for one render pass. So we
  89 | // have to use this unstable API to ensure it batches them. (2019/12/03)
  90 | // https://github.com/facebook/react/issues/14259#issuecomment-439702367
> 91 | ReactDOM.unstable_batchedUpdates(() => {
     | ^  92 |   const onContextChange = EDITOR_TO_ON_CHANGE.get(e)
  93 | 
  94 |   if (onContextChange) {
View compiled
(anonymous function)
./src/create-editor.ts:86
  83 | 
  84 |   Promise.resolve().then(() => {
  85 |     FLUSHING.set(editor, false)
> 86 |     editor.onChange()
     | ^  87 |     editor.operations = []
  88 |   })
  89 | }
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Pull request closed without merging**
