### PR TITLE
fix:  chinese input double in qq browser

### PR DESCRIPTION
**Pull request by onionRunning**
Fixes: # fix chinese double input on qq browser

### CODE REVIEW

**Comment by onionRunning** [comment]
@ianstormtaylor

**Comment by moonrailgun** [comment]
@ianstormtaylor Hi, this pr looks like very well. Is any updates on that issue?

**Review by dylans — CHANGES_REQUESTED** [review]
Apologies that this one has sat for so long. We've had a lot of similar fixes for other browsers recently.

To land this we need a rebase against main and a changeset, and then it should be pretty trivial to land this. Thanks @onionRunning.

**Comment by dylans** [comment]
I've rebased and updated this in #4452 , thanks. Closing!

**Comment by YaoKaiLun** [comment]
I am not sure why did this. I tried to use "sougo input method" to input chinese in qq browser in windows and it can not works，and then i tried to comment the code，it worked well.

image

qqbrowser


image

**Pull request closed without merging**
