### PR TITLE
Ios autocorrect buffer

### LINKED ISSUE #1471: *bug* iOS backspace and enter keystrokes not registering correctly with autocorrect.
**What is the current behavior?**
1) When pressing backspace, the iOS autocorrect bar does not register the change. For example if you type "The", and then delete all the characters to "", the iOS autocorrect bar still thinks "The" is the current state. If you then type "none", it thinks you've typed "Thenone".
2) When pressing enter, the iOS autcorrect bar does not register the change. For example, if you type "none<enter>pere" it thinks you typed "nonepere" (one word, no space).

slate_ios_autocorrect

**What is the expected behavior?**
1) When pressing backspace, the iOS autocorrect bar should update appropriately.
2) When pressing enter, the iOS autocorrect bar should update appropriately.

**Which versions of slate and which browser / OS are affected by this issue?** 
Tested on iOS safari with:
"react": "16.2.0",
"react-dom": "16.2.0",
"slate": "0.31.7",
"slate-react": "0.10.22"

Note that draft.js has a very similar issue (cf. https://github.com/facebook/draft-js/issues/1574)

### PR DESCRIPTION
**Pull request by davidlibland**
This builds of the work of @rgrove to make sure that the iOS autocomplete buffer is correctly updated on Backspace and Return keystrokes.

Fixes #1471

We handle backspace and return keystrokes as part of the `KeyDown` events rather than in `onNativeBeforeInput`. This makes slate more extensible - plugins generally override slate's default behavior for those keystrokes from within `KeyDown` events. Placing the functionality in `onNativeBeforeInput` means those plugins might need to override it as well.
In particular, the changes in this PR make `slate-edit-list` compatible with the iOS autocomplete buffer (once a small update has been made to that plugin); i.e. it helps resolve the issue noted [here](https://github.com/ianstormtaylor/slate/pull/1475).

I would love to get @rgrove 's comments on this PR.

### CODE REVIEW

**Comment by rgrove** [comment]
@davidlibland It looks like this incorporates my changes from PR #1475, differing only in how the `keydown` `preventDefault()` call is avoided. Seems okay to me, but I'm on vacation at the moment and haven't tested it.

Given that there are extraneous commits in this PR that aren't really relevant to Slate, it seems like the cleanest approach might be to add this change to my PR, no? Or if @ianstormtaylor doesn't mind the extra commits, he could just merge this one and close mine. In any event, only one PR or the other can be merged, since they conflict.

**Comment by rgrove** [comment]
This PR has been superseded by #1475 and #1520, so it can be closed.

**Comment by ianstormtaylor** [comment]
Thanks @rgrove!

**Comment by ianstormtaylor** [comment]
And thanks @davidlibland for your work on this!

**Pull request closed without merging**
