### PR TITLE
Fix triple select bug

### PR DESCRIPTION
**Pull request by sethmcleod**
This relates to issue #752 and is still a work in progress. Just wanted to go ahead and open a PR as I debug this issue to keep discussion in one place.

The idea is to update the selection conditionally if it has been _triple selected_ (similar to how Draft.js [does it](https://github.com/facebook/draft-js/blob/213cd764f61cc64552bddd672ae1748529d55333/src/model/modifier/RichTextEditorUtil.js#L262-L265)) in order to avoid the next block from being selected.

Here is the info I've found so far:

image

It seems when the next block is selected, it becomes the focus. I wonder what the best way to update the focus/selection is...

### CODE REVIEW

**Comment by sethmcleod** [comment]
@ianstormtaylor are you aware of any other cases where `focusKey !== anchorKey && anchorOffset === 0 && focusOffset === 0` would return true? Also, would you mind adding an _in progress_ label to this?

**Comment by sethmcleod** [comment]
I've added some code to **moveToRange** of the **startBlock**, and that seems to work pretty well. The only problem I can find is that if the user _undos_ their changes afterward, the block contents (anchorRanges) get reversed. Here's what it looks like when I triple-click to select the first row (then the selection is adjusted) then I click backspace, then CMD+Z

image

**Comment by ianstormtaylor** [comment]
Hey @sethmcleod thanks for this! Looking at this, and how Draft.js does it, I'm remebering a previous conversation in https://github.com/ianstormtaylor/slate/pull/863#issuecomment-307659171 where I realized that I don't think this is the best way for us to solve it.

Instead, since it seems like the thing that really trips people up is "which blocks are affected when I select then do `x`..." it seems like we might just want to edit the `getBlocksAtRange()` methods logic to omit blocks that happen to have the trailing/leading hanging selection in them. Does that make sense? I'd love a PR that implements that. I think it should solve the same issue, but in a way that has less problems going forward. Thanks!

**Comment by sethmcleod** [comment]
Ohh that makes sense @ianstormtaylor, thanks for the reply. I'm going to close this PR and I'll work on updating the `getBlocksAtRange()` logic in another PR.

**Pull request closed without merging**
