### PR TITLE
fix: IME repeat input

### PR DESCRIPTION
**Pull request by gyh9457**

### CODE REVIEW

**Comment by timbuckley** [comment]
Is there a test you could write that would cover this change? Was there an issue that describes the bug being fixed?

**Comment by gyh9457** [comment]
IME-repeat

as shown above

when I use IME to input, `onBeforeInput` and `onCompositionEnd` will be triggered at the same time
so it repeats the input twice

There are no unit test in `slate-react`，so I won’t add test cases for now

@timbuckley

**Comment by githoniel** [comment]
I can confirm this bug exist in chrome x65 75.0.3770.80 in Win10

**Comment by thezero** [comment]
Is there anything blocking this PR from being merged?

**Comment by ianstormtaylor** [comment]
Thanks @gyh9457!

**Pull request merged**
