### PR TITLE
Fix addMark/removeMark caused unexpected onChange.

### PR DESCRIPTION
**Pull request by ulion**
**Description**
Collaborate editor relies on onChange and editor.operations, but in editor.addMark and editor.removeMark, onChange is called directly without check it was already scheduled by editor.apply method. which will cause onChange with same group or part of same group of editor.operations be called twice, then cause problem with collaborate editors.

**Issue**
Fixes: (link to issue)

**Context**
This PR simply check whether there was already a scheduled onChange, if so, do not call onChange in addMark and removeMark.

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

### CODE REVIEW

**Review by TheSpyder — APPROVED** [review]
Looks good to me, nice catch!

This will still lead to possibly unexpected change events (when `editor.operations` is an empty array) but at least that shouldn't cause any problems.

**Comment by ianstormtaylor** [comment]
@ulion can you add a changeset please? Thanks. (Or allow edits to your branch so that I can do it myself.)

**Comment by ulion** [comment]
> @ulion can you add a changeset please? Thanks. (Or allow edits to your branch so that I can do it myself.)

invited you with write access.

**Comment by ianstormtaylor** [comment]
Thanks @ulion!

**Pull request merged**
