### PR TITLE
Remove `renderPlaceholder`

### PR DESCRIPTION
**Pull request by ianstormtaylor**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Improvement.

#### What's the new behavior?

This pull request changes the placeholder logic to use decorations instead of the one-off `renderPlaceholder` middleware, which makes it more flexible. It also fixes some issues related to selection tracking that created placeholder-related bugs.

#### How does this change work?

The placeholder logic is packaged as a separate `slate-react-placeholder` plugin, which can be used for custom placeholders. (Or for super custom use cases you can write your own.)

The `<Editor>` component will now automatically add an instance of the `slate-react-placeholder` component to its stack when it receives a `placeholder=` prop, to best emulate regular DOM editors. But by omitting this prop you can handle the behaviors completely on your own instead.

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x] The relevant examples still work. (Run examples with `yarn watch`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: https://github.com/ianstormtaylor/slate/issues/2067
Fixes: https://github.com/ianstormtaylor/slate/pull/2168
Fixes: https://github.com/ianstormtaylor/slate/issues/2257
Fixes: https://github.com/ianstormtaylor/slate/issues/1678
Fixes: https://github.com/ianstormtaylor/slate/issues/1344

### CODE REVIEW

**Comment by garth** [comment]
I don't see any documentation on how to get placeholders working after this change. Simply having a placeholder prop on editor does not work, adding the new placeholder package as a plugin causes render mark to be called with a type of 'placeholder', but if render mark returns a value then it becomes editable (not a placeholder)?

**Comment by ianstormtaylor** [comment]
@garth make sure you have the latest two versions of `slate` and `slate-react`. There was a bug fix in `slate` that is required, and I forgot to bump the peer deps until `.1` of this new release.

**Comment by garth** [comment]
@ianstormtaylor yes, I have the latest version of all slate packages, but still can't get the placeholder working. I've tried a few different ways to get it working, but not had any luck so far. Is there an example of how to use the new version?

**Comment by ianstormtaylor** [comment]
@garth most of the existing examples use a `placeholder=` prop and they seem to work.

**Comment by garth** [comment]
ok, I found the problem. The signature for `renderMark` and `renderNode` has been changed. So next() was never called.

**Comment by garth** [comment]
BTW: the typescript typings have not been updated, which is why I didn't pick this up earlier.

```
[ts] Type '(props: RenderNodeProps, editor: Editor, next: () => any) => any'
  is not assignable to type '(props: RenderNodeProps, next: () => void) => any'.
```

**Comment by cudr** [comment]
Hello, @ianstormtaylor! Now it looks, like we can use only one placeholder text multiple times, because first placeholder plugin render text each time.  Maybe we can change it to multiple different placeholders? I mean, maybe we can we pass placeholder text to decorator for that?

**Comment by svenadlung** [comment]
Looking for the same as @cudr. Changing the placeholder dynamically would be awesome.

**Comment by cudr** [comment]
Make PR for that (#2416 )

**Pull request merged**
