### PR TITLE
Update products to include Cake

### PR DESCRIPTION
**Pull request by ericedem**
Now that Cake is coming out of invite only mode, figured it was a good time to add it as a product using Slate. :)

Link to https://www.cake.co/

### CODE REVIEW

**Comment by ericedem** [comment]
@oyeanuj I had to built something custom because there wasn't really anything out there that was still maintained and fully featured.

We just launched this feature, but I have a strong desire to open source it. It's almost there, but needs some TLC like API cleanup and some strong documentation / examples.

**Comment by ianstormtaylor** [comment]
Awesome, thank you @ericedem! Congrats on the launch!

**Comment by oyeanuj** [comment]
@ericedem Open-sourcing it would be amazing, it is the one functionality that there aren't many options for! 

If that is going to be a while, it will super useful to get a sense of the broader contours of how you set it up - inlines vs marks, data flow, etc.

And congrats on the launch!

**Comment by ericedem** [comment]
@oyeanuj Yea it will probably be a while, we are a small team so until we grow a bit it will be hard  to maintain an open source project full time.

When I get some time I'll write something up about the approach we took.

**Comment by oyeanuj** [comment]
> When I get some time I'll write something up about the approach we took.

Thanks, looking forward to it!

**Pull request merged**
