### PR TITLE
Fixes minor grammatical issues in documentation

### PR DESCRIPTION
**Pull request by bjorntheart**

### CODE REVIEW

**Comment by lcswillems** [comment]
@bjorntheart But your change introduces a new typo, isn't? It should be `rolled up into` instead of `rolled up up`.

**Comment by CameronAckermanSEL** [comment]
@lcswillems  aw man, sorry. Totally missed that 😆 Thanks for pointing it out

**Comment by lcswillems** [comment]
I made a PR to fix this: https://github.com/ianstormtaylor/slate/pull/3511

**Comment by bjorntheart** [comment]
🤦‍♂ Sorry about that @lcswillems, and thanks for the PR

**Pull request merged**
