### PR TITLE
[On Development] Prepare for React-v17

### PR DESCRIPTION
**Pull request by zhujinxuan**
This PR changes the `componentWillRecieveProps` to make it more alike `getDerivedStateFromProps`

Then when react v17 is released or when we decide to move to React v16 and drop v15 support, then we can easily change the `componentWillRecieveProps` to `getDerivedStateFromProps`

### CODE REVIEW

**Comment by zhujinxuan** [comment]
@SamyPesse I did not know that polyfill.  I think that polyfill works better.

I will colse this PR;

**Comment by SamyPesse** [comment]
@zhujinxuan I was not suggesting that we should close this Pr, but instead switch the code to use the React16/17 APIs (such as `getDerivedStateFromProps`) now in this PR and setup the polyfill.

**Comment by zhujinxuan** [comment]
@SamyPesse Ohhhh, my mistake.  I reopen this PR and will finish this three weeks later.

**Comment by zhujinxuan** [comment]
Close this PR; the lifecycle works will be in https://github.com/ianstormtaylor/slate/pull/1975

**Pull request closed without merging**
