### PR TITLE
Extract hotkey and environment detection into separate packages

### PR DESCRIPTION
**Pull request by justinweiss**
Overriding default behavior in plugins can be hard, because you have to match all of the keybindings that Slate uses. By exporting hotkeys as its own package, both core Slate plugins and custom plugins can use the same key detection logic.

This is a first stab at pulling this logic out -- let me know what you think!

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
@justinweiss this looks great! Thank you for doing this and for carrying over the changes to meticulously.

I'm thinking we should maybe name the hotkeys functions `Hotkeys.is*` with the `is` prefix to parallel some of the other boolean logic we've got. Are you okay to make that change?

**Comment by justinweiss** [comment]
@ianstormtaylor Yep! Not a problem.

**Comment by tobiasandersen** [comment]
This is awesome @justinweiss, looking great!

**Comment by ianstormtaylor** [comment]
Thank you @justinweiss, this PR is amazing.

**Pull request merged**
