### PR TITLE
FIX Links to examples of the README.md

### PR DESCRIPTION
**Pull request by dubzzz**
#### Is this adding or improving a _feature_ or fixing a _bug_?

No

#### What's the new behavior?

Links are working fine now.

Before: Links towards examples were broken

#### How does this change work?

Links are working fine now

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #
Reviewers: @

### CODE REVIEW

**Comment by dubzzz** [comment]
@timbuckley Do you believe we could merge this fix so that the documentation links towards the right urls?

**Comment by cpprookie** [comment]
> @timbuckley Do you believe we could merge this fix so that the documentation links towards the right urls?

I have closed my duplicated pr, @dubzzz  you should keep this one open and fix legacy links.

**Comment by dubzzz** [comment]
@timbuckley Sorry for the ping, any updates?

**Comment by ianstormtaylor** [comment]
Added on `master`. Thank you @dubzzz!

**Pull request closed without merging**
