### PR TITLE
Use children

### PR DESCRIPTION
**Pull request by Mangatt**
**Description**
This is tiny change from `Children` component to `useChildren` hook. This is not breaking because `Children` was not public endpoint. This change allows traversing children with `React.Children`.

**Issue**
Fixes: #3966 

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

(Other changes were performed by` yarn fix`, only relevant file changes are in `use-children.tsx`, `editable.tsx` and `element.tsx`.)

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Beautiful PR, thanks @Mangatt!

**Review by ianstormtaylor — APPROVED** [review]

**Comment by Mangatt** [comment]
Thanks, @ianstormtaylor , glad to do my part!

**Comment by Mangatt** [comment]
Do you think @thesunny that this could be merged into next `next` / `0.60.5` update? As mentioned, it does not change anything for anyone, but opens large possibilities for new plugins. And it's already approved by Ian.

**Comment by thesunny** [comment]
I'm going to wrap up TypeScript within the next week. I think we can have more regular merges soon afterwards.

You may need to check the plugin against the TypeScript changes but assuming that's done, I don't see a reason why it couldn't be added relatively quickly. I'm hoping we can get everything out of `@next` released into `@latest` releases as well.

**Comment by Mangatt** [comment]
Do you think that can be merged anytime soon, @thesunny ?

**Comment by thesunny** [comment]
Hi @Mangatt,

I have no problem with merging the code but for some reason it seems to be trying to change all of Ian's `.github` templates. Do you have any idea what's going on there?

If we can fix this, I can merge.

**Comment by ianstormtaylor** [comment]
Might be a Prettier issue and we need to add the templates to `.prettierignore`? Not sure.

**Comment by thesunny** [comment]
I added the templates to `.prettierignore` yesterday so that I could add prettier back to linting.

I think you're right though and Mangatt merged before that was in place.

I wonder if we could manually copy and paste those templates into this PR and the issue would go away? I'm afraid I'm one of those people that don't really know how git works underneath so not sure if that is the right way to fix it.

**Comment by thesunny** [comment]
Merged this PR with reverted `.github` files in this PR #4152

**Pull request closed without merging**
