### PR TITLE
[WIP] Add onMouseMove method; Fix incorrect selection when click and drag move

### PR DESCRIPTION
**Pull request by zhujinxuan**
#### Is this adding or improving a _feature_ or fixing a _bug_?

bug

#### What's the new behavior?

If user click and drag, and an selection event is fired during dragging.  Then we shall expect an extended range instead of an collapsed range.  When the browser accidentally causes an collapsed range, then we shall extend it to the new selection instead of select.

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x] The relevant examples still work. (Run examples with `yarn watch`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: https://github.com/ianstormtaylor/slate/issues/1969
Reviewers: @

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Hey @zhujinxuan, this sounds like a good call. Can you explain exactly what's going on here in terms of the events that are firing in the browser? I'm not sure I understand.

**Comment by zhujinxuan** [comment]
@ianstormtaylor Sometimes, when you press and drag from a empty block start.  The browser will fire onSelection events with collapsed selection, rather than selection extended from the mouse down selection.  (https://github.com/ianstormtaylor/slate/issues/1969)

This PR tries to fix the problem that, for any `onSelection` event during onMouseMove, if the left key is pressed when mouse moves (click and drag) and if the previous selection and current selection is both collapsed,  we identify that the bug occurs.  Then we fix the selection with extending between  previous and current selection.

**Comment by zhujinxuan** [comment]
@ianstormtaylor I can only reproduce it in the slate.  I can only reproduce https://github.com/ianstormtaylor/slate/issues/1969#issue-341029949 but unable to reproduce https://github.com/ianstormtaylor/slate/issues/1969#issuecomment-411570384.  (only able to reproduce the zero-width condition but not the second one). 

Can we just change this PR to add onMouseMove handlers (without adding the timer to the core)? 
 Then a temporary solution can be provided as a plugin.

**Comment by zhujinxuan** [comment]
@ianstormtaylor BTW, the timer is initialized only on (pressed & mouse move).  Because the setTimeout is called only when (event.buttons % 2 == 1) (which means left mouse button is pressed)

But I agree the timer solution is an ugly solution.

**Comment by zhujinxuan** [comment]
Will use another PR to fix the problem

**Pull request closed without merging**
