### PR TITLE
Fix composition input on Safari (native InputEvents)

### PR DESCRIPTION
**Pull request by beldar**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Bug fix

#### What's the new behavior?

Composition events are now handled on native InputEvents

#### How does this change work?

It would allow accented characters (i.e à, ò, ï, â, etc)

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x] The relevant examples still work. (Run examples with `yarn watch`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #2499

### CODE REVIEW

**Comment by AlesJiranek** [comment]
@ianstormtaylor  Hi, Is there any idea when this will be merged?

**Comment by evasteingrims** [comment]
Is there any news on when this will be merged? @ianstormtaylor?

**Comment by ianstormtaylor** [comment]
I'm not sure about how this works. IME support has been a long-running issue, and something that seems fairly complex, so I'm unsure if this handles the cases properly. Check the existing issues we've got going to see prior discussions.

**Comment by knubie** [comment]
@ianstormtaylor I have a more complete description of the issue in my PR #3040.

That said I think the approach taken in this PR is also valid, and even addresses an issue that mine does not (canceling IME input should leave it in the composition text in place).

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.

**Pull request closed without merging**
