### PR TITLE
Fixed mentions example

### PR DESCRIPTION
**Pull request by nadeemshaik**
#### Is this adding or improving a _feature_ or fixing a _bug_?
Fixing a bug

#### How does this change work?
I have made some minor changes to get the mentions example working.

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x] The relevant examples still work. (Run examples with `yarn watch`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #2826 
Reviewers: @ianstormtaylor

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Thanks @nadeemshaik!

**Comment by MatthewHerbst** [comment]
I'm finding that `this.editor.current.setAnnotations(annotations);` doesn't work for me. When I click into my editor after adding the mentions example's code, I get this:

```
_this3.editor.current.setAnnotations is not a function
```

Is there any reason why the editor might not be available on its ref?

I use `this.editor = React.createRef();` to create the ref in my `constructor`, and and pass it `ref={this.editor}` to the `Editor`. Did I miss something?

**Comment by MatthewHerbst** [comment]
Upon closer look, `setAnnotations` does not appear to be a method on the editor, only `setAnnotation` is. Is that correct?

**Comment by nadeemshaik** [comment]
@MatthewHerbst That was the issue (missing `setAnnotations` method). I have added the method and a few other things in this PR.

**Comment by MatthewHerbst** [comment]
Ah, got it. THANK YOU @nadeemshaik !

@ianstormtaylor any chance we could please get this in a patch release before the next minor/major release?

**Comment by AntonAL** [comment]
I have installed "slate": "^0.47.4" and "slate-react": "^0.22.4", but the issue is not resolved for me.
I'm still getting `editor.setAnnotations is not a function` error…
Is a patch is released?

**Comment by lupos** [comment]
Following. Also need this fix.

**Comment by anshudwibhashi** [comment]
Same ^^ I just updated slate and slate-react to the latest versions listed on the Github readme, and I still have the issue.

**Comment by scottluptowski** [comment]
I am also experiencing the `editor.setAnnotations is not a function` issue

**Comment by scottluptowski** [comment]
> editor.setAnnotations is not a function

I tried getting around this error by adding `setAnnotations` to a `commands` object in a plugin and copy+pasting the definition used in this PR.

Instead I see this error:
> Annotation.createList is not a function

Which seems a bit unusual due to the swap from `createList` to `createMap`

**Comment by anshudwibhashi** [comment]
Another thing I tried is just looping through the annotations map and adding each annotation manually because `addAnnotation` is a method that I know for a fact exists, but when I do that it seems like it has no effect and the `renderAnnotation` method is never called. The `Suggestions` component seems to update just fine with the correct suggestions. It just displays them at (-1000, -1000), the default position, because it can't find the anchor.

**Comment by anshudwibhashi** [comment]
Update: The `addAnnotation` workaround actually seems to (almost) do the trick. The annotations are actually being added, but the `renderAnnotation` method seems to never be called. This seems to be a known issue: https://github.com/ianstormtaylor/slate/issues/2909

**Comment by lupos** [comment]
incase it's unclear to anyone im pretty sure this is fixed but they just need to release a new version. if you can't wait you can always download the source and include it manually until they update NPM.

commit in question is [here](https://github.com/ianstormtaylor/slate/commit/5471343ae84d24ee05173de48a0d5a5c47a5d7d4)

**Comment by JoeCase** [comment]
@ianstormtaylor Any news on the updated package release? Tried every workaround above to no avail. Just switched from draft JS to Slate. Loving how much easier it is to navigate and build on, but the mentions is a crucial functionality I need. Actually switched specifically for those. 

If anyone has found a viable workaround would love to hear about it. Tried the looping, the source import, tried putting in the setAnnotations from the source manually but got the Annotation.createList is not a function error as well.

**Comment by JoeCase** [comment]
Finally got a workaround working if anyone comes across this. I put the source folders for both slate and slate-react packages from the dowloaded repo into my project. Then in my component:
`import { Editor } from [path to local slate folder]
import { Value } from [path to local slate-react folder]`
THEN had to redirect the editor import in the local slate-react editor component to point to the local slate folder. So in local slate-react/components/editor.js... 
change
`import { Editor as Controller } from 'slate'`
to
`import { Editor as Controller } from '[path to local slate folder]'`

Then it all works fine. 

Absolutely loving slate after switching from draft-js. So much easier to navigate and build on.

**Comment by lupos** [comment]
@JoeCase Thanks for this. I was trying to do this as well the other day and almost got it sorted but I am attempting to use "yarn/npm link". May be worth looking into for you.

**Comment by JoeCase** [comment]
Credit to @lupos for suggesting to download the source. I never would have thought to do it. I tried all the previous methods to no avail. Hopefully the new package is live on npm soon. Hoping to break this functionality out into a plugin with key commands.

**Comment by JoeCase** [comment]
Adding in case anyone still needs to hack this. It's a crucial element to my app so been patching away:

The local source folder imports worked fine in dev but crashed in production because in production `Object.keys(Editor.proptypes)`  in `local-slate-react/components/editor.js` and `Object.keys(Content.propTypes)` in `slate-react/components/editor.js` were crashing things because the propTypes were being stripped out because of [this rule.](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-foreign-prop-types.md)

Tried all day to get npm link working but couldn't so just went in and assigned those manually to a variable:

`const editorProptypes = ["autoCorrect", "autoFocus", "className", "defaultValue", "id", "onChange", "options", "placeholder", "plugins", "readOnly", "role", "schema", "spellCheck", "style", "tabIndex", "value", "onBeforeInput", "onBlur", "onClick", "onContextMenu", "onCompositionEnd", "onCompositionStart", "onCopy", "onCut", "onDragEnd", "onDragEnter", "onDragExit", "onDragLeave", "onDragOver", "onDragStart", "onDrop", "onInput", "onFocus", "onKeyDown", "onKeyUp", "onMouseDown", "onMouseUp", "onPaste", "onSelect"]
const domProps = omit(this.props, editorProptypes)`
 and
`const contentProptypes = ["autoCorrect", "className", "contentKey", "editor", "id", "readOnly", "role", "spellCheck", "style", "tabIndex", "tagName"]
const domProps = omit(this.props, contentProptypes)`

I'm on a hard deadline so doing whatever I can to get this to work and wanted to share but it might not be the most elegant. If anyone has a better solution or could get the npm link to work would love to clean it up. 

Really hoping the new version is released soon.

**Pull request merged**
