### PR TITLE
fix(content): use handlers that actually exist in event listeners

### PR DESCRIPTION
**Pull request by ericedem**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Fixing a _bug_

#### How does this change work?

In a recent change, handlers now only exist in `Content#handlers` and not directly on the instance itself. There were still a couple of places where they were being accessed directly from the instance for event listeners. This was causing some side effects in iOS.

More details in #2125 

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x] The relevant examples still work. (Run examples with `yarn watch`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #2125 #2129 
Reviewers: @zhujinxuan @ianstormtaylor

### CODE REVIEW

**Comment by zhujinxuan** [comment]
Hi, @ericedem  Can you also update the componentWillUnmout's removeEventListener in https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/components/content.js#L116

**Comment by ericedem** [comment]
@zhujinxuan nice catch! Whoops.

It looks like this PR is blocked because the code coverage hasn't changed. With this patch, what is the best way to deal with this? I don't see any tests for `content.js`.

**Comment by zhujinxuan** [comment]
@ericedem codecov does not block merging process.  We do not care for the codecov with slate-react right now because it is not able to be tested with jsdom.  Hopefully we may have slate-react tested with chrome headless next year.

**Comment by isubasti** [comment]
The same reason seems to break safari on OSX as well. if you create a new block and start typing and try going back to the very first character using arrow keys, it has an extra cursor position. This PR seems to fix it

**Comment by ianstormtaylor** [comment]
Thank you @ericedem for catching this! Sorry for the delay.

**Comment by ericedem** [comment]
@ianstormtaylor No problem, thanks for maintaining! 🍻

**Comment by zarv1k** [comment]
@ianstormtaylor Seems, this PR (slate-react@0.18.4) breaks focus in empty editor:
1. Select all and delete all content https://www.slatejs.org/#/rich-text
2. Blur editor (click outside the editor)
3. Try to add some text into the editor. The editor loses focus immediately.

There is no such issue in slate-react@0.18.3.

**Comment by ericedem** [comment]
@zarv1k Thanks for reporting. Can you file a separate issue for it for tracking the issue? Something to check is whether you see the issue in 0.36.x, since this PR fixes a bug introduced in 0.37.x that may have covered it up.

**Comment by zarv1k** [comment]
@ericedem, The issue I described above is related only to this PR, it is not related to slate package at all, it's related to slate-react package only. There is no issue in slate@0.40.2+slate-react@0.18.3, but as you can see it is reproduced on top versions of slate packages with slate@0.40.2+slate-react@0.18.4. Just try to reproduce using in my comment above).
I can create the separate issue in a few hours if needed.

**Comment by zarv1k** [comment]
I've created the issue: https://github.com/ianstormtaylor/slate/issues/2147

**Comment by briandk** [comment]
👍 

I second @zarv1k - I was dealing with this very bug this morning. I was just about to file an Issue when I saw they had already filed one: #2147 😇

**Pull request merged**
