### PR TITLE
Address doc suggestion in #644

### PR DESCRIPTION
**Pull request by oyeanuj**
Just a small edit that we discussed in #644.

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Hey @oyeanuj this section refers to the data model, so I think the bit about containing DOM elements is strange?

**Comment by oyeanuj** [comment]
Yea, I agree. Maybe I'll move it to FAQs and add more details. In general, I feel like a lot of the questions that come up here or on Slack could be answered in a new section called 'Recipes' or maybe added to FAQs.

Thoughts?

**Comment by ianstormtaylor** [comment]
Adding things to FAQs works for me. I'd also be down to have a `general/patterns.md` doc that had examples of common patterns if you wanted to start it. Thanks!

**Comment by oyeanuj** [comment]
I've moved this to FAQ, reverting the model documentation to what it was. I'll keep in mind the patterns page and create one when I am confident of a few patterns that I am using or seeing floating around.

**Comment by ianstormtaylor** [comment]
Perfect! Thank you @oyeanuj :smile:

**Pull request merged**
