### PR TITLE
Convert setBlock and setInline to plurals for more intuitive naming.

### LINKED ISSUE #567: change `setBlock` and `setInline` to be plurals
I keep getting tripped up and forgetting that they impact all of the currently selected blocks and inlines, since their name isn't great. Better as:

```
setBlocks()
setInlines()
```

So it maps more intuitively to the blocks/inlines from:

```
state.blocks
state.inlines
```

### PR DESCRIPTION
**Pull request by schneidmaster**
Fixes #567

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Thank you @schneidmaster! I'm going to wait on this one for the next major release, since it's a breaking change.

Can you add in shimmed `setBlock/setInline` transforms for each of the ones that was renamed, and use `slate-dev-logger` with the `logger.deprecate(...` syntax to make it easier to migrate? That's what we've been doing for renames like this in the past to make it easier for people to see where deprecated methods are being called from. Thanks!

**Comment by schneidmaster** [comment]
@ianstormtaylor done!

**Comment by schneidmaster** [comment]
@ianstormtaylor Can you ping me when you're ready to merge and I'll resolve the conflicts? It's a bit tedious keeping this one up-to-date given the number of changed lines

**Comment by ianstormtaylor** [comment]
Hey @schneidmaster I'd be down to merge this today I think if you can rebase. Thank you!

**Comment by schneidmaster** [comment]
@ianstormtaylor rebased!

**Pull request merged**
