### PR TITLE
add setTextByKey function/test

### PR DESCRIPTION
**Pull request by zGrav**
Should add functionality required for #1547 

@ianstormtaylor , this is my first time implementing a 'full functionality' into slate, sorry if this is wrong way to approach it, would appreciate some pointers 👍

### CODE REVIEW

**Comment by zhujinxuan** [comment]
How to undo the operation?

**Comment by justinweiss** [comment]
I would be _very_ hesitant to add new primitive operations into Slate -- each one has to support undo / inverse, and will likely add a lot of complexity when Slate supports collaborative editing. 

Is this something that could be handled using `insert_text` / `remove_text` instead? It wouldn't be atomic, but there are a lot of change operations (like `wrapBlockByKey`) that are built out of several primitive operations.

**Comment by CameronAckermanSEL** [comment]
IMO this will be a lot harder to implement an undo because the current `invert` feature doesn't have completely solid approaches for undoing changes where the original state is not somehow cached in the operation. 

slate-auto-replace has some code that shows how to delete and @zhujinxuan posted (what I'm really sure is) a functional code snippet that achieves this.

https://github.com/ianstormtaylor/slate-plugins/blob/master/packages/slate-auto-replace/src/index.js#L49

@zGrav  thanks for taking the initiative to provide this feature

**Comment by zGrav** [comment]
@justinweiss since @zhujinxuan has given a solution that might work in the issue itself and due to the complexity of adding primitive ops into Slate, I'll close this issue as of now.

I appreciate the look anyway!

**Pull request closed without merging**
