### PR TITLE
Rewrite drag&drop code related to void nodes.

### PR DESCRIPTION
**Pull request by AlbertHilb**
The state of drag&drop in Slate is far from perfect especially when void nodes are involved (see #1170 and #1192 for examples).

This PR aims to solve some of those problems.

First of all, `onDragEnter`, `onDragLeave` and `onDrop` `Void` handlers are removed . That code is a bit tricky (among other things it temporally changes the editable state of the node content) and we can live without it.

In place of the removed code, a new function, `getDropPoint`, is added to `utils`.
It returns the document point (key and offset) for a drop event.
The point is chosen following the rules below:

1. if the drop event DOM target is inside an inline void node, the point is the first position of the next sibling text node if the event happens closer to the right side of the void node, the last position of the previous sibling text node otherwise.

1. If the drop event DOM target is inside a block void node, the point is the first position of the next sibling block node if the event happens closer to the lower side of the void node, the last position of the previous sibling block node otherwise.

1. If the drop event DOM target isn't inside a void node, the point is the caret position where the drop occurred as in the current code.

`getDropPoint` is used by `onDrop` `Content` handler to get the Slate drop action target.

Since void nodes are now valid DOM drop targets, `isInEditor` checks within `Content` drag&drop handlers are removed.
However, `isInEditor` was used also to avoid managing drag&drop events coming from other editor instances embedded inside the first. To keep that behavior, the new code prevents those events from bubbling up calling `stopPropagation`.

A problem this PR leaves open is the drag feedback effect not in sync with drop action: dragging over a void node, you miss a caret showing where the insert point is, for example.
To fix this, I guess, the only solution is to not let the browser draw the feedback, doing it by ourselves.
On drag over events we could call `getDropPoint` to determine where is the insertion point and then draw a fake caret there.
If you want I can try to add this in a future PR.

Let me know your opinion, I'm open to all changes you believe are needed. :blush:

### CODE REVIEW

**Comment by oyeanuj** [comment]
@AlbertHilb This is great, as it also solves for #980. Just wanted to point out that for `isInEditor`, @ianstormtaylor had earlier suggested breaking it into two different functions: `isInEditor` and `isEditableInEditor`. I started a PR  #1027 for that but I think this PR should subsume that PR and those changes can probably be incorporated in this one - let me know!

> A problem this PR leaves open is the drag feedback effect not in sync with drop action: dragging over a void node, you miss a caret showing where the insert point is, for example.
To fix this, I guess, the only solution is to not let the browser draw the feedback, doing it by ourselves.
On drag over events we could call getDropPoint to determine where is the insertion point and then draw a fake caret there.
If you want I can try to add this in a future PR.

Maybe we could add this to the Image or Embed example?

**Comment by ianstormtaylor** [comment]
@AlbertHilb thank you for this! Sorry for the delay. This PR looks really well done.

I like the idea for the `getDropPoint` util. I'm sure we can tweak little pieces of logic in the future if we realize we need to. Looks good to me!

Question for you that doesn't block the merge: Will the `onDragOver` and `onDragEnter` events in `<Void>` not propagate up to the `<Content>` component? Is that why we need to retain the `e.preventDefault` in them? Otherwise it would be cool to move it all into the `core.js` plugin.

**Comment by AlbertHilb** [comment]
Hi @ianstormtaylor.

Of course, `onDragOver` and `onDragEnter` events bubble up to the `Content` component and they could be handled there. But the default action should be prevented only when the target is inside a `Void` node and deciding, from within `Content`, if a DOM element is inside a void node requires a bit of extra logic and slightly more resources, so for the moment I think it is better to leave those handlers into `Void` component.

About the second question, I think that after the refactoring in #1231, moving `onDrop` logic to `core.js` does not make sense anymore, since `core.js` should not contain code (like `getBoundingClientRect()`) directly interacting with browsers.

**Comment by ianstormtaylor** [comment]
@AlbertHilb actually I think `plugins/core.js` is okay to have browser code. I've been going that way more and more over time. It gets passed an instantiated React component anyways, so those handlers will only ever fire when the components are mounted in the browser.

**Comment by AlbertHilb** [comment]
@ianstormtaylor.

I understand your position, but I think we should distinguish between lower and higher level browser code.
The logic which, using `getBoundingClientRect()`, determines if the target of a drop event is on the left or on the right of an inline void node, for example, is so fundamental that an editor based on Slate can hardly work without it.
However, if that piece of code is moved to `core.js`, then anyone wanting to personalize drop behavior would have to rewrite it, because it would be overridden by his custom drop handler.

**Comment by ianstormtaylor** [comment]
@AlbertHilb I'm not sure. If someone overrides it, there's a decent chance they're doing something completely different, and thus don't need it. (Although I think it would be nice to package up as an exposed utility function.)

As long as there are a few utils exposed, and as long as people are returning early when they don't want to override, I feel like it will be okay.

**Comment by AlbertHilb** [comment]
@ianstormtaylor 

> I'm not sure. If someone overrides it, there's a decent chance they're doing something completely different

For example, one can want to keep the "default" drop target but to insert a rendered math formula if the (external) dropped text is TeX code.

**Comment by echenley** [comment]
Seems like using stopPropagation here leads to some undesirable behavior: https://github.com/ianstormtaylor/slate/issues/1277

**Pull request merged**
