### PR TITLE
Error when deselecting or pasting: Cannot add property 0, object is not extensible

### PR DESCRIPTION
**Pull request by jacob-lcs**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Fixes: #4034
Reviewers: @thesunny

### CODE REVIEW

**Comment by jacob-lcs** [comment]
I install the "@babel/helper-call-delegate" to pass deploy/netlify

**Comment by BrentFarese** [comment]
I think #3850 takes care of this?

**Comment by jacob-lcs** [comment]
> I think #3850 takes care of this?

Yes, he solved the problem

**Comment by BrentFarese** [comment]
> > I think #3850 takes care of this?
> 
> Yes, he solved the problem

Closing as a duplicate of #3850.

**Pull request closed without merging**
