### PR TITLE
fix: cursor jumps more than one character unexpectedly

### PR DESCRIPTION
**Pull request by unageek**
**Description**
This PR fixes the issue where the editor cursor jumps more than one character unexpectedly while you are navigating with arrow keys. The issue occurs when the cursor is around a digit, an asterisk, or a number sign.

**Issue**
Fixes: #4649
Fixes: #4655
Fixes: #4659

**Example**
https://user-images.githubusercontent.com/29035331/142804562-bbba8f7a-4c04-4066-a3c3-4b97d2f2e32c.mp4

Tested with Safari 15.1.

**Context**
The new code implements Unicode's [grapheme cluster boundary specification](https://www.unicode.org/reports/tr29/#Default_Grapheme_Cluster_Table), which defines general rules for breaking Unicode text into individual characters.

The character sets in the regular expressions are generated from [`GraphemeBreakProperty.txt`](https://www.unicode.org/Public/UCD/latest/ucd/auxiliary/GraphemeBreakProperty.txt) with the following script (`regex.sh`):

```bash
#!/usr/bin/env bash
grep "; $1 " GraphemeBreakProperty.txt | sed -E 's/ .*//; s/[0-9A-F]+/\\u&/g; s/[0-9A-F]{5}/\{&\}/g; s/\.\./-/' | tr -d '\n'
```

and command lines:

```bash
./regex.sh Prepend
./regex.sh SpacingMark
./regex.sh L
./regex.sh V
./regex.sh T
./regex.sh LV
./regex.sh LVT
```

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [x] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

### CODE REVIEW

**Comment by unageek** [comment]
I'm going to refine the rules based on Unicode's [Default Grapheme Cluster Boundary Specification](https://www.unicode.org/reports/tr29/#Default_Grapheme_Cluster_Table). So I convert this back to draft while I'm working on it.

**Comment by unageek** [comment]
Now it's ready for review!

**Review by dylans — APPROVED** [review]
Thanks @unageek, it looks good to me. I'm going to leave it open for a couple of days in case anyone else has time to review. Otherwise we'll land this week as part of the next release. 🍻

**Comment by oliger** [comment]
Thanks @unageek! This looks great! Slate really needed a proper way to split grapheme clusters.

**Pull request merged**
