### PR TITLE
Add Products: Taskade

### PR DESCRIPTION
**Pull request by 1c7**
Hi, I know one of the co-founder of [Taskade](https://www.taskade.com/): [John Xie](https://www.linkedin.com/in/johnxie/)   
[Taskade](https://www.taskade.com/)'s editor is really impressive.      

image

I know Slate.js because of Taskade.

I think Taskade should be in the list.
Thanks

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Very cool @1c7! Can you fix the pull request to keep the list in alphabetical order? Thanks!

**Comment by 1c7** [comment]
no problem :) I would change it now

**Comment by 1c7** [comment]
done~, please merge

**Comment by ianstormtaylor** [comment]
Thanks @1c7!

**Pull request merged**
