### PR TITLE
Fix cursor movement in RTL elements (#2963)

### PR DESCRIPTION
**Pull request by SophiaSaiada**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Fixing a bug (#2963).

#### What's the new behavior?

Fix cursor movement in RTL elements. 

#### How does this change work?

On each left/right key click - the code evaluates the direction of the current paragraph and based on that decides whether moving right or left.

#### Have you checked that...?

Yep.

#### Does this fix any issues or need any specific reviewers?

Fixes: #2963
Reviewers: -

### CODE REVIEW

**Comment by diedsmiling** [comment]
We urgently need this fix, can this PR please get some attention?

**Review by diedsmiling — APPROVED** [review]

**Comment by asfktz** [comment]
Hi there 👋

I wish so much for this PR to merge 🙏

Can I help with anything to make it happen?

**Comment by CodeMouse92** [comment]
We do indeed need this fix landed.

**Comment by ianstormtaylor** [comment]
Thank you for this @SophiaSaiada, sorry for the delay, but great PR.

**Pull request merged**
