### PR TITLE
Fix several undo/redo issues related to selection operation

### PR DESCRIPTION
**Pull request by sgurenkov**
#### Is this adding or improving a _feature_ or fixing a _bug_?
_bug_

Should fix the following issues: #2891, #2729

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x] The relevant examples still work. (Run examples with `yarn watch`.)

### CODE REVIEW

**Comment by laufeyrut** [comment]
@ianstormtaylor Do you think you could review this PR 🙏

**Comment by ianstormtaylor** [comment]
Thanks @sgurenkov!

**Comment by bryanph** [comment]
I'm wondering if we can get by without storing set_selection operations? In what cases would you like to "undo" a selection? Or in what cases does a selection influence the behavior of an undo? Can't we just make sure that all operations are undone whilst setting the selection to some sane place?

**Comment by ianstormtaylor** [comment]
@bryanph I don't think Slate currently does it properly, but ideally the selection would be undone to where it was at the time of the operation. I think Google Docs does this properly.

**Comment by evasteingrims** [comment]
This does not totally fix #2891. Redos are still lost on selection change

see: 
not-fixed

**Pull request merged**
