### PR TITLE
Add replaceNodeByKey change

### PR DESCRIPTION
**Pull request by skogsmaskin**
This follows up https://github.com/ianstormtaylor/slate/pull/665.

Add ``change.replaceBlock(oldBlock, newBlock)`` method to replace a block with another block.

Remove code that replaced an empty block in ``.insertBlock``

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Hey @skogsmaskin this is great!

I think we should call this method `replaceNodeByKey` to match the other ones that take a specific node as input, and also not to mention block because it doesn't appear block-specific?

Thanks!

**Comment by skogsmaskin** [comment]
@ianstormtaylor, good points!  I have updated the PR. Not sure about the options.normalization though, is it necessary?

**Comment by ianstormtaylor** [comment]
Nice, looks perfect @skogsmaskin, thank you!

I just realized this is a breaking change for people currently relying on `insertBlock`, so I'm going to label it as such and wait for another breaking release to merge this in, to try to lessen the number of breaking releases a bit. Hope that's okay!

**Comment by skogsmaskin** [comment]
@ianstormtaylor yes there is no rush :+1:

**Pull request merged**
