### PR TITLE
Path parameter in NodeMatch function

### PR DESCRIPTION
**Pull request by Mangatt**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Feature

#### What's the new behavior?

Match function now gets second parameter with node path.

#### How does this change work?

It is non-breaking change.

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #3967

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
I can't remember for sure, but I believe we used to do this before and changed it to only take a `node` because there are a few places where a `path` is not available to matching functions—potentially normalization. Not entirely sure, but worth checking on.

**Comment by BrentFarese** [comment]
@Mangatt it seems this PR only changes the implementation for `Editor.nodes`, but there are other locations in the codebase where a `NodeMatch` function is used.  Can you change those locations too?  We shouldn't update the documentation or the TS interface for `NodeMatch`, I wouldn't think, until all places in the code that use a `NodeMatch` function are called with `match(n, p)`.

**Comment by reinvanimschoot** [comment]
@BrentFarese I'm working on another PR with all match functions changed to `match(n, p)`. That being said, so far I've only noticed one other places where `match(n, p)` is explicitly called and not deferred to `Editor.nodes` which is `Editor.levels`. 

All `Transform` functions seem to make use of `Editor.nodes` for their match functionality and so do most of the other `Editor` functions.

 I am I missing another place where there is an explicit `match` function called?

**Comment by BrentFarese** [comment]
> @BrentFarese I'm working on another PR with all match functions changed to `match(n, p)`. That being said, so far I've only noticed one other places where `match(n, p)` is explicitly called and not deferred to `Editor.nodes` which is `Editor.levels`.
> 
> All `Transform` functions seem to make use of `Editor.nodes` for their match functionality and so do most of the other `Editor` functions.
> 
> I am I missing another place where there is an explicit `match` function called?

I would look to see everywhere where the `NodeMatch` type is used in the code base, and then perhaps do a global find for `match` to see all the locations where the `match` parameter is used in a `Transform` or an `Interface`.

**Comment by reinvanimschoot** [comment]
The thing is that the `Transforms` do not use the `NodeMatch` type, but `(node: Node) => boolean`, which might also be soemthing to clean up along the way. But I'll take a look at it.

**Comment by BrentFarese** [comment]
> The thing is that the `Transforms` do not use the `NodeMatch` type, but `(node: Node) => boolean`, which might also be soemthing to clean up along the way. But I'll take a look at it.

Ah I see.  Yes if you're able to clean up the usage of that type, that would be a benefit too!

**Pull request closed without merging**
