### PR TITLE
Allow nodes to hold `null` properties

### PR DESCRIPTION
**Pull request by aglundahl**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Improving the API.

#### What's the new behavior?

Currently, Transforms.setNodes equates `null` with `undefined`, so any property set to `null` will be removed from the node.

This change preserves `null` properties and ensures that only `undefined` properties are removed. The reason why we want this behavior is because we want the type for a property to be explicitly `prop: number | null` and not `prop?: number | null`. We need the nil value to be explicit, because we work a lot with partial nodes (property diffs) and it also works better with JSON serialization.

I haven't found the motivation behind the initial design, but maybe there's a good reason to keep the current behavior. There has been [some discussions](https://github.com/ianstormtaylor/slate/pull/3353) about removing `Transforms.unsetNodes`, though, which obviously collides with this change.

#### How does this change work?

Instead of a loose equality check for `value == null` (which includes both `null` and `undefined`), I strictly check for `value === undefined` before removing the property.

#### Have you checked that...?

- [X] The new code matches the existing patterns and styles.
- [X] The tests pass with `yarn test`.
- [X] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [X] The relevant examples still work. (Run examples with `yarn start`.)

#### Does this fix any issues or need any specific reviewers?

Reviewers: @thesunny @CameronAckermanSEL @ianstormtaylor @BrentFarese

### CODE REVIEW

**Review by BrentFarese — APPROVED** [review]

**Review by ianstormtaylor — CHANGES_REQUESTED** [review]
The reason for equating `null` and `undefined` was that JSON strips undefined values during serialization, so for OT-style editors we needed to have a way to declare a property should be unset. Instead of opting for an additional `unset_node` operation, we went with `set_node` with `null`. Here's the thread with the original discussion: https://github.com/ianstormtaylor/slate/issues/3007#issuecomment-541747562

I think it would be nice to be able to have `null` at the top-level, but not that this would require creating an `unset_node` operation.

**Comment by aglundahl** [comment]
@ianstormtaylor Ah, I didn't think about the serializability of operations. We don't have that use case (yet). Thanks for the added context!

I think having an `unset_node` operation would improve the API, and I'd be happy to make the required changes if you also think it's an improvement? It's definitely a breaking change, though, so we'd have to plan the release of it accordingly.

**Comment by ianstormtaylor** [comment]
@aglundahl thank you, adding `unset_node` sounds good to me! Be careful to make it so that `unset_node` is invertible, so it'll need to contain enough information to re-set the properties like the others.

**Comment by TheSpyder** [comment]
Adding a new operation is a huge undertaking for collaboration integrations. I'm not saying we can't do it, but we need to be really careful.

Likewise a change to make `null` values not mean "remove property" in `set_node` would break a lot of things. I don't really understand the use case for allowing null values?

**Comment by aglundahl** [comment]
@TheSpyder I'm not using Slate right now, and I'm afraid I don't have time to finish this, so I'm okay with closing this. Unless @BrentFarese or @timbuckley have any objections?

**Comment by TheSpyder** [comment]
All good. We’re clearing out old PRs; this can be reopened (or resubmitted) if it needs to be later.

**Pull request closed without merging**
