### PR TITLE
Fix for Editor.positions not working correctly in all cases

### PR DESCRIPTION
**Pull request by spocke**
#### What's the new behavior?

Here is an example of the bug on the official https://www.slatejs.org/examples/links demo page:
link_caret_issue

When arrowing right over over the last character it skips to the next line. The caret is supposed to be placed after the `!` in this case.

#### How does this change work?

There is an end case in the code where it will break the advance iteration of the current text node if the current string buffer is empty. But when the buffer is empty there might still be valid positions to return. The distance state determines if the previous advance overflowed the text node length and by how much so this change checks if the string is empty and that the distance is null meaning it will continue to advance and yield positions for the remaining distance.

This PR adds a few unit tests that previously was not passing. It also adds a few tests for things that doesn't seem covered but related to this change just to make sure it doesn't break those cases.

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #
Reviewers: @

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Hey @spocke this looks like a good call.

Can you add tests for the `word/line` units? I'm curious to see if it still properly jumps over whole words/lines despite the inline being in the middle of the word. Thanks!

**Comment by spocke** [comment]
Yes, my initial fix here was incorrect for the word and line units. I think it's just a matter of not stopping the advance from happening if there is still things in distance to advance. I changed the code and added two test for fragmented words and lines and it seems to work.

**Comment by ianstormtaylor** [comment]
@spocke beautiful, thank you!

**Review by ianstormtaylor — APPROVED** [review]

**Comment by jacob-lcs** [comment]
Hi~Can this PR be merged?

**Pull request merged**
