### PR TITLE
Improvement/get path

### PR DESCRIPTION
**Pull request by jtadmor**
#### Is this adding or improving a _feature_ or fixing a _bug_?

 feature (perf enchancement)

#### What's the new behavior?

with the new changes to path, we are often calling `node.getPath(arg)`. until the code base is fully built around paths instead of keys, the argument is often a key (in normalization, range creation, various getters, etc.)

this then calls `getKeysToPathsTable` to create a `{ [key]: path }` dictionary. unfortunately, this dictionary is created new with every call, even if the nodes haven't changed!

#### How does this change work?

much like react's fancy tree-diffing, each node stores one version of its own local `dict`. only when the nodes have changed from the last check-up will the new one be calculated. 

this means that subsequent calls to `document.getPath(key)` will be much faster if no change has occurred to the `nodes` (e.g. when the only change is moving the focus, or if we do multiple look-ups while executing a single change).

it also means that if one part of the tree changes, many nodes might still be able to return their cached copies, making re-creating this `dict` much faster.

(another potential approach would be to not have this method build a full `dict`, and rather just return early when we find node with the correct key.)

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [ ] The relevant examples still work. (Run examples with `yarn watch`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #
Reviewers: @

### CODE REVIEW

**Comment by jtadmor** [comment]
benchmarks
    changes
      ✔ add-mark: 140.84 -> 132.11 ops/sec (7.00% slower)
      ✔ delete-backward: 119.80 -> 117.10 ops/sec (2.00% slower)
      ✔ delete-forward: 135.54 -> 129.70 ops/sec (5.00% slower)
      ✔ insert-node-by-key: 234.30 -> 218.05 ops/sec (7.00% slower)
      ✔ insert-text-by-key: 272.04 -> 274.31 ops/sec (0.84% faster)
      ✔ insert-text: 212.71 -> 213.83 ops/sec (0.53% faster)
      ✔ normalize: 294.43 -> 334.51 ops/sec (13.61% faster)
      ✔ remove-node-by-key: 141.28 -> 141.50 ops/sec (0.16% faster)
      ✔ set-blocks: 229.70 -> 215.95 ops/sec (6.00% slower)
      ✔ split-block: 85.60 -> 79.56 ops/sec (8.00% slower)
    models
      ✔ from-json-big: 4.02 -> 3.89 ops/sec (3.00% slower)
      ✔ from-json: 432.49 -> 389.40 ops/sec (11.00% slower)
      ★ get-active-marks-at-range:
            user: 4210.69 -> 13119.62 ops/sec (211.58% faster 🙌 )
            real: 4893.01 -> 20357.63 ops/sec (316.06% faster 🙌 )
      ★ get-ancestors:
            user: 4136.07 -> 8089.88 ops/sec (95.59% faster)
            real: 4707.84 -> 10025.83 ops/sec (112.96% faster 🙌 )
      ✔ get-blocks-at-range: 1413.66 -> 1471.19 ops/sec (4.07% faster)
      ✔ get-blocks: 10234.69 -> 8146.34 ops/sec (26.00% slower)
      ★ get-common-ancestor:
            user: 5269.24 -> 33656.54 ops/sec (538.74% faster 🙌 )
            real: 6025.36 -> 57126.64 ops/sec (848.10% faster 🙌 )
      ★ get-descendant:
            user: 4908.84 -> 16450.30 ops/sec (235.12% faster 🙌 )
            real: 5516.13 -> 23971.86 ops/sec (334.58% faster 🙌 )
      ★ get-furthest-ancestor:
            user: 5556.61 -> 48626.93 ops/sec (775.12% faster 🙌 )
            real: 6377.18 -> 116043.97 ops/sec (1719.68% faster 😱 )
      ★ get-inlines-at-range:
            user: 1457.74 -> 1920.94 ops/sec (31.78% faster)
            real: 1756.71 -> 2382.42 ops/sec (35.62% faster)
      ✔ get-inlines: 14114.91 -> 12456.36 ops/sec (13.00% slower)
      ✖ get-leaves:
            user: 2735707.38 -> 1549540.15 ops/sec (77.00% slower)
            real: 3565088.41 -> 2956142.50 ops/sec (21.00% slower)
      ★ get-marks-at-range:
            user: 1017.70 -> 1369.34 ops/sec (34.55% faster)
            real: 1339.02 -> 1900.99 ops/sec (41.97% faster)
      ✔ get-marks: 3591.68 -> 3375.94 ops/sec (6.00% slower)
      ★ get-parent:
            user: 4843.01 -> 20111.88 ops/sec (315.28% faster 🙌 )
            real: 5481.61 -> 29324.95 ops/sec (434.97% faster 🙌 )
      ★ get-path:
            user: 5717.79 -> 65105.43 ops/sec (1038.65% faster 😱 )
            real: 6559.26 -> 199235.19 ops/sec (2937.46% faster 😱 )
      ★ get-texts-at-range:
            user: 3265.63 -> 7087.38 ops/sec (117.03% faster 🙌 )
            real: 3729.00 -> 8717.49 ops/sec (133.78% faster 🙌 )
      ✔ get-texts: 14719.76 -> 14365.35 ops/sec (2.00% slower)
      ★ has-node-multiple:
            user: 3852.43 -> 9732.98 ops/sec (152.65% faster 🙌 )
            real: 4271.08 -> 12065.56 ops/sec (182.49% faster 🙌 )
      ★ has-node:
            user: 4804.15 -> 18876.44 ops/sec (292.92% faster 🙌 )
            real: 5426.19 -> 26854.78 ops/sec (394.91% faster 🙌 )
      ✔ to-json: 2701.92 -> 2432.91 ops/sec (11.00% slower)
    html-serializer
      ✔ deserialize: 19.65 -> 18.00 ops/sec (9.00% slower)
      ✔ serialize: 682.17 -> 642.95 ops/sec (6.00% slower)
    plain-serializer
      ✔ deserialize: 2451.58 -> 2565.38 ops/sec (4.64% faster)
      ✔ serialize: 5002.02 -> 4915.16 ops/sec (2.00% slower)
    rendering
      ✔ decoration: 89.63 -> 82.01 ops/sec (9.00% slower)
      ✔ normal: 109.41 -> 104.00 ops/sec (5.00% slower)

**Comment by jtadmor** [comment]
(i'm not sure why `get-leaves` is so much slower)

**Comment by ianstormtaylor** [comment]
Hey @jtadmor, thanks for investigating this!

We actually have a similar memoization technique that we use for some of the `Node` (and other model) methods right now. I added `getKeysToPathsTable` to it with the hope of doing exactly as you describe, which [you can see here](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/node.js#L2216).

But I'm curious about these performance benchmarks, because they look good. It might be possible that the difference is purely the overhead in the caching techniques (since the `memoize` helper is currently more abstract by necessity). If that's so, I'd agree that these numbers seem amazing enough to warrant doing a custom solution for the `keys -> paths` table since it's such a core use case.

If you remove the `'getKeysToPathsTable'` entry in the `memoize` helper, do you see losses/gains? (With/without the changes in the pull request applied.)

**Comment by jtadmor** [comment]
thanks for the reply. since this is my first forray into benchmarks, im not exactly sure if the huge gains in that benchmark are just because this caching is unaffected by `resetMemoization` or whether it represents an actual improvement.

so the first thing i tried was just commenting that `resetMemoization` out on master.
```
      ★ get-path:
            user: 5717.79 -> 21234.51 ops/sec (271.38% faster 🙌 )
            real: 6559.26 -> 26214.91 ops/sec (299.66% faster 🙌 )
```

faster, but not nearly as much (kinda surprising).

then i tried removing `'getKeysToPathsTable'` from `memoize` on master: `~1/2 - 1/5` perf hits across the board (vs. master). not great.

then i realized that `memoize` isn't even doing any checks on whether `this.nodes` has changed (or any similar checks), which makes sense because we typically just create a new `Node` from scratch when something has changed.

so i tried removing `'getKeysToPathsTable'` from `memoize` on this branch and further optimizing by not doing the `this.nodes === this.__lastNodes` check:

```
benchmarks
    changes
      ✔ add-mark: 140.84 -> 132.37 ops/sec (6.00% slower)
      ✔ delete-backward: 119.80 -> 124.96 ops/sec (4.31% faster)
      ✔ delete-forward: 135.54 -> 135.64 ops/sec (0.07% faster)
      ✔ insert-node-by-key: 234.30 -> 265.41 ops/sec (13.28% faster)
      ✔ insert-text-by-key: 272.04 -> 288.69 ops/sec (6.12% faster)
      ✔ insert-text: 212.71 -> 216.75 ops/sec (1.90% faster)
      ✔ normalize: 294.43 -> 345.28 ops/sec (17.27% faster)
      ✔ remove-node-by-key: 141.28 -> 152.24 ops/sec (7.76% faster)
      ✔ set-blocks: 229.70 -> 215.84 ops/sec (6.00% slower)
      ✔ split-block: 85.60 -> 82.09 ops/sec (4.00% slower)
    models
      ✔ from-json-big: 4.02 -> 4.04 ops/sec (0.43% faster)
      ✔ from-json: 432.49 -> 411.82 ops/sec (5.00% slower)
      ★ get-active-marks-at-range:
            user: 4210.69 -> 14125.38 ops/sec (235.46% faster 🙌 )
            real: 4893.01 -> 23790.13 ops/sec (386.21% faster 🙌 )
      ★ get-ancestors:
            user: 4136.07 -> 12586.44 ops/sec (204.31% faster 🙌 )
            real: 4707.84 -> 16687.45 ops/sec (254.46% faster 🙌 )
      ★ get-blocks-at-range:
            user: 1413.66 -> 2255.11 ops/sec (59.52% faster)
            real: 2027.28 -> 3544.51 ops/sec (74.84% faster)
      ✔ get-blocks: 10234.69 -> 10141.09 ops/sec (1.00% slower)
      ★ get-common-ancestor:
            user: 5269.24 -> 46596.87 ops/sec (784.32% faster 🙌 )
            real: 6025.36 -> 100429.38 ops/sec (1566.78% faster 😱 )
      ★ get-descendant:
            user: 4908.84 -> 19477.43 ops/sec (296.78% faster 🙌 )
            real: 5516.13 -> 28172.90 ops/sec (410.74% faster 🙌 )
      ★ get-furthest-ancestor:
            user: 5556.61 -> 58791.52 ops/sec (958.05% faster 🙌 )
            real: 6377.18 -> 151385.26 ops/sec (2273.86% faster 😱 )
      ★ get-inlines-at-range:
            user: 1457.74 -> 1867.77 ops/sec (28.13% faster)
            real: 1756.71 -> 2458.21 ops/sec (39.93% faster)
      ✔ get-inlines: 14114.91 -> 13900.18 ops/sec (2.00% slower)
      ✔ get-leaves: 2735707.38 -> 2212886.64 ops/sec (24.00% slower)
      ★ get-marks-at-range:
            user: 1017.70 -> 1314.80 ops/sec (29.19% faster)
            real: 1339.02 -> 1788.58 ops/sec (33.57% faster)
      ✔ get-marks: 3591.68 -> 3428.43 ops/sec (5.00% slower)
      ★ get-parent:
            user: 4843.01 -> 21524.84 ops/sec (344.45% faster 🙌 )
            real: 5481.61 -> 30992.23 ops/sec (465.39% faster 🙌 )
      ★ get-path:
            user: 5717.79 -> 70729.49 ops/sec (1137.01% faster 😱 )
            real: 6559.26 -> 235049.57 ops/sec (3483.47% faster 😱 )
      ★ get-texts-at-range:
            user: 3265.63 -> 7028.84 ops/sec (115.24% faster 🙌 )
            real: 3729.00 -> 8894.37 ops/sec (138.52% faster 🙌 )
      ✔ get-texts: 14719.76 -> 14899.61 ops/sec (1.22% faster)
      ★ has-node-multiple:
            user: 3852.43 -> 10839.09 ops/sec (181.36% faster 🙌 )
            real: 4271.08 -> 13458.17 ops/sec (215.10% faster 🙌 )
      ★ has-node:
            user: 4804.15 -> 19403.27 ops/sec (303.89% faster 🙌 )
            real: 5426.19 -> 28315.20 ops/sec (421.82% faster 🙌 )
      ✔ to-json: 2701.92 -> 2701.27 ops/sec (0.00% slower)
    html-serializer
      ✔ deserialize: 19.65 -> 18.25 ops/sec (8.00% slower)
      ✔ serialize: 682.17 -> 643.58 ops/sec (6.00% slower)
    plain-serializer
      ✔ deserialize: 2451.58 -> 2587.34 ops/sec (5.54% faster)
      ✔ serialize: 5002.02 -> 4742.24 ops/sec (5.00% slower)
    rendering
      ✔ decoration: 89.63 -> 87.23 ops/sec (3.00% slower)
      ✔ normal: 109.41 -> 110.02 ops/sec (0.56% faster)
```

certainly looks better.

but on that note, i am a little uncertain how safe it is not to be doing those checks in the memoization. i might be missing something but if someone does something like:
`change.insertBlock(someExistingNode.set({ nodes: newNodes }))`

doesn't that same `Node` object persist? the memoization seems like it will potentially return erroneous results in that case.

might be missing something here.

**Comment by ianstormtaylor** [comment]
Ahhh okay, I think I know what's going on. Thanks for the writeup @jtadmor that helped a lot. It actually makes sense now that you mention it that this pull request appears to be a lot faster...

Currently we use the `utils/memoize` helper to memoize methods on immutable objects. Because of how Immutable.js works, we'll get new instances of those objects each time they change, with the memoize cache removed. We're basically using the "always return a new instance" property of immutable objects to make caching easy. So we never need to worry about the cache being out of date, because it only gets reset when something changes.

But, the `utils/memoize` module also exports some other helpers, which are used in the benchmarks to `resetMemoization` so that the benchmarks in question are testing the actual logic inside the memoized methods instead of the memoization logic speed. Otherwise all subsequent calls would just return the same cached result.

By using an alternative memoization technique for this one method, the cache wasn't being reset between runs, such that it seemed like there was a huge performance gain. But really it's just a difference in cache resetting—since the `utils/memoize` was being reset each time it effectively wasn't enabled, whereas the `this._*` cache doesn't have a reset switch, so it was permanently cached.

---

PS. cc @benjycui @zhujinxuan I think this same kind of this was happening to create the differences between #1811 and #1818 in terms of benchmarks. Not that it matters anymore, but just so we know for next time we use them!

**Comment by jtadmor** [comment]
ok, i suspected that might be the case. we can probably just close this, ill continue to investigate some other approaches.

**Comment by ianstormtaylor** [comment]
Sounds good, thanks for your help @jtadmor!

**Pull request closed without merging**
