### PR TITLE
add guard checks for value and editor in <Slate />

### PR DESCRIPTION
**Pull request by rockettomatooo**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Bug

#### What's the new behavior?

An error message is displayed when the user passes faulty values to `<Slate />`:
image
(I passed `null` as value)

#### How does this change work?

`value` and `editor` props passed to `<Slate />` are checked with `Node.isNodeList()` and `Editor.isEditor()`.

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

#### Does this fix any issues or need any specific reviewers?

--

### CODE REVIEW

**Comment by rockettomatooo** [comment]
Unfortunately, there are no tests setup for `slate-react`. I tested this with an example (See the screnshot above).

Also the linter doesn't like my `console.error()`. I dunno if it's maybe better to throw an error instead (for a stacktrace maybe) but that would also kill the whole editor.

**Comment by ianstormtaylor** [comment]
Hey @rockettomatooo can you use the `tiny-invariant` package for this? That's what we've used in the past. 

Also I think those lines should be moved inside the `useMemo` callback, just to make them slightly less frequent (although it's still fairly often).

**Comment by rockettomatooo** [comment]
Hi @ianstormtaylor I now added the `tiny-invariant` package as a dependency to `slate-react` and moved the guard checks into the `useMemo` callback.
Also I merged my branch with the current master as there was a conflict with my first commit.

**Comment by CameronAckermanSEL** [comment]
(FYI I resolved the merge conflict in package.json)

**Comment by ianstormtaylor** [comment]
Thanks @rockettomatooo! Sorry for the delay.

**Pull request merged**
