### PR TITLE
remove more core `key` usage

### PR DESCRIPTION
**Pull request by ianstormtaylor**
This removes more of the `key` usage in Slate's core. We'll need to remove all of it in order to get to #2495, so this is one step in that direction.

---

###### BREAKING

**Slate's handler signatures have changed.** Previous there were inconsistencies in the ordering of arguments to Slate handlers, which were separated into "commands", "queries" and "middleware". These inconsistencies added complexity, and the distinctions between handlers wasn't actually necessary. Now there is only a single handlers concept.

```js
// Before, for middleware...
onKeyDown: (...args, editor, next) => {}

// Before, for commands and queries...
insertImage: (editor, ...args) => {}
isActive: (editor, ...args) => {}

// After, for all handlers...
handler: (fn, editor) => (...args) => {}
```

Not only has the signature changed, but the "middleware stack" has been removed too, in favor of function composition. So the `fn` argument to handlers is actually the old function that existed that the handler is overriding. If you want to pass through to it, you call it just like a normal function:

```js
// Before, deferring to the stack...
middleware: (...args, next) => {
  next()
}

// After, deferring to the wrapped function...
handler: (fn, editor) => (...args) => {
  return fn(...args)
}
```

**Slate commands and queries are no longer chainable.** As part of streamlining the handlers, we need to be able to return values from them. And so we have to remove the old logic that always returned `this` for chaining.

**Calling unknown handlers on the editor will now throw.** Previously these would just do nothing silently, but now they will throw an error saying that the handler was not registered by any of the plugins.

---

###### NEW

**The new `editor.exec` method replaces old handler invoking.** This is the new method for calling handlers dynamically using a `(name, ...args)` signature. All handlers are still exposed directly as methods on the editor as well.

```js
editor.exec('insertText', ...)
```

---

###### DEPRECATED

**The `editor.run`, `editor.query` and `editor.command` methods are deprecated.** All of these have been replaced by the new `editor.exec` which can return values, make changes, and respond to events.

**All of the getters on `Value` objects are deprecated.** All of the getter shorthands on `Value` objects are now deprecated. The full list includes:

**All of the manipulation methods on `Value` objects are deprecated.** Previously you could call these methods and receive a new immutable value object as a return value. The full list includes:

```
value.addAnnotation()
value.addMark()
value.insertNode()
value.insertText()
value.mergeNode()
value.moveNode()
value.removeAnnotation()
value.removeMark()
value.removeNode()
value.removeText()
value.setAnnotation()
value.setMark()
value.setNode()
value.setProperties()
value.setSelection()
value.splitNode()
```

To achieve this now you'll have to use `editor.applyOperation` instead. This ensures that all changes to a value go through the operations pipeline and can be normalized by a schema. This was an advanced feature and this change won't affect most people.

---

Fixes: https://github.com/ianstormtaylor/slate/issues/1883
Fixes: https://github.com/ianstormtaylor/slate/issues/2321
Fixes: https://github.com/ianstormtaylor/slate/issues/2812
Fixes: https://github.com/ianstormtaylor/slate/issues/2746
Fixes: https://github.com/ianstormtaylor/slate/issues/2711
Fixes: https://github.com/ianstormtaylor/slate/issues/2985
Fixes: https://github.com/ianstormtaylor/slate/issues/2858
Fixes: https://github.com/ianstormtaylor/slate/issues/2002

### CODE REVIEW

**Comment by BrentFarese** [comment]
@ianstormtaylor do you have any idea when this PR will be merged into master?  We are working on a complex Slate editor implementation right now and it seems like a number of breaking changes are in here.  Wondering when they will hit...

Thanks.

**Comment by BrentFarese** [comment]
@ianstormtaylor thank you!  If that branch is public or referenced in an issue somewhere, it'd be great if you can let me know here and I can take a look.

**Comment by ianstormtaylor** [comment]
@BrentFarese it's not public nope. We've talked a little about it in the Slack contributing channel but that's it.

**Comment by ianstormtaylor** [comment]
Closing in favor of https://github.com/ianstormtaylor/slate/pull/3093.

**Pull request closed without merging**
