### PR TITLE
Fix backspace first void block and delete last void block (#357)

### PR DESCRIPTION
**Pull request by kiliwalk**
- Fix backspace first void block, see #357
- Fix delete last void block in empty document

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Hey @kiliwalk thanks for submitting this! Can you add a test that ensures that we don't accidentally break this functionality in the future? Thanks!

**Comment by skogsmaskin** [comment]
I think this also need patching for ``deleteForward``. It has the same symptoms - if it is a void-node at the end of the document.

**Comment by kiliwalk** [comment]
@ianstormtaylor That's ok, I will append tests later.
@skogsmaskin Already included in this fix

**Comment by skogsmaskin** [comment]
@kiliwalk - i have to applied your patch (thank you btw), it works well for void-nodes in the beginning of the document, but it seems like we still have issues for void-nodes in the end of the document. Also void-nodes after each other in the middle of the document.

**Comment by kiliwalk** [comment]
@skogsmaskin Could you give a detail case? As I tested, there is no problem with delete-forwad last void block in document

**Comment by skogsmaskin** [comment]
@kiliwalk try inserting three void-nodes (only) in the document. Focus last or second node and press backspace. I get ``node.js:107 Uncaught Error: Could not find a descendant node with key "nm02".``.

Deleting the first void-node always works fine.

**Comment by kiliwalk** [comment]
@skogsmaskin Oh yeah, you are right, but it's delete-backward issue. I'd like to try to fix these together

**Comment by kiliwalk** [comment]
The [fix backspace the void block continuously](https://github.com/ianstormtaylor/slate/pull/360/commits/1b5f8e4835978c1dca62617d16ddc10d2a1154fe) commit tries to fix this problem:
1. Drop two images to the empty editor, then the document only has three image blocks, no others like paragraph
2. Now current selection is on the last image, and the offset is 1(not 0)
3. Backspace will emit error
4. Click the last image, now the selection offset is 0
5. Backspace successfully
6. Now selection is on the first image, and the offset is 1
7. Since backspace will fail on offset=1, so click then backspace, but error occurs since there is nothing in document. Accutually, we should create an empty paragraph.

With this commit, backspace will be ok when offset=1, and will insert an empty paragraph when document is empty

**Comment by skogsmaskin** [comment]
It works fine now, but one thing - the use of paragraph node type. As @ianstormtaylor commented on my pull request (https://github.com/ianstormtaylor/slate/pull/371#issuecomment-252321491), should not be acknowledged by slate core.

Not sure how fix this otherwise though.

**Comment by ianstormtaylor** [comment]
Ah yup, as @skogsmaskin mentioned, we should avoid anything that requires Slate being opinionated about a specific `node.type` value. If that gets fixed this sounds good to go!

**Comment by kiliwalk** [comment]
@ianstormtaylor So is there any method like `document.createEmpty()` to insert a empty node? I have no idea how to replace specifying paragraph type, please give some advices  if possible

**Comment by ianstormtaylor** [comment]
@kiliwalk good question. I think maybe the error that is thrown when the document is empty should be fixed, to make that a valid state, and then when deleting it can just remove the node and not insert anything new. What is that error by the way?

**Comment by kiliwalk** [comment]
The error is like `Uncaught Error: Could not find a descendant node with the key "xxxx"`, and thrown at `moveTo` method since deleting the only one void node there is no other nodes in the document

**Comment by ianstormtaylor** [comment]
Hey @kiliwalk sorry for the long delay here. The error when deleting the first void block in a document has been fixed now thanks to some other refactoring.

There is still the issue that you cannot delete the last void node in a document if it's the only node left, and I think the core of Slate alone can't solve this problem for you, other than leaving you with an empty document which isn't helpful. Instead, if you're dealing with this situation, I'd recommend adding your own custom schema rule that enforces that the void nodes in question are always followed by another node.

I'm going to close this pull request since we can't solve it this way without forcing Slate to care about the nodes in your schema. Thank you for the help you, and for prompting the discussion!

**Comment by erquhart** [comment]
@ianstormtaylor it seems that rules are only run for a node when the node itself is changed - if I delete all of the nodes around the void node, the rule is never triggered. Is this expected?

**Comment by erquhart** [comment]
Update for anyone else who stumbles here: the document itself can be validated, and that happens on every change.

**Pull request closed without merging**
