### PR TITLE
readme: minor fix for updated contributing link

### PR DESCRIPTION
**Pull request by udayanshevade**
**Description**

Wanted to refresh my mind on the contributing guidelines, and saw that the link no longer worked, so just thought to update it really quick.

### CODE REVIEW

**Comment by thesunny** [comment]
@udayanshevade That seems like it would be helpful. May I recommend that it points to the online documentation instead as it will be easier to read. It's also consistent with the fact other links point to online URLs as well.

[https://docs.slatejs.org/general/contributing](https://docs.slatejs.org/general/contributing)

With that change, I can merge the PR

**Comment by udayanshevade** [comment]
Sure thing. I thought about whether to point it to the docs but just went with how it had been before. Let me push the link to the site instead.

**Comment by thesunny** [comment]
Thanks! Merged.

**Comment by TheSpyder** [comment]
There are actually two links to contributing, you fixed the one at the end but there's another at the top 🤭

**Pull request merged**
