### PR TITLE
Fix duplicated content after drag and drop

### PR DESCRIPTION
**Pull request by llevequeblup**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Fixing a bug

#### What's the new behavior?

When drag and dropping text on Firefox, or more complex objects on all browsers, actually move the drag and dropped item instead of simply copying it

#### How does this change work?

Previously the beforeinput event with deleteByDrag inputType was relied on to clean dragged item, but this event is not thrown in Firefox, and neither in Chrome for non-textual content.
This change reproduce behaviour found in v0.47 : a flag is set when dragging starts, cleared if dragging stops, and checked when dropping content to delete the old selection.

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #3137, probably #3522

### CODE REVIEW

**Comment by rabiesnoussi** [comment]
Hi @llevequeblup does these changes fix the problem ?

**Comment by llevequeblup** [comment]
Yes they do

**Comment by rabiesnoussi** [comment]
Cool !! Is it going to be merged soon, or does it need more tests before ?

**Comment by CameronAckermanSEL** [comment]
Hey @llevequeblup, thank you for the PR. When I took a look at this and tested it on chrome, I noticed that while the latest version of the slate examples has functional drag and drop for normal text, the deployment for this PR doesn't remove the old text anymore. I haven't yet tried it from Firefox, and I also can't see what part of the PR might have lead to this regression.

When you have a free moment, lemme know what you think!

**Comment by Arcainne** [comment]
Any update on this? Would love to see this issue fixed for dragging and dropping void elements. :)

**Comment by llevequeblup** [comment]
When I tested drag and drop of normal text on Chrome, I figured out that it worked only if the source and target were not in the same span (I am not sure why).
If I drag and drop text from one place of a span to another place of the same span, the text always get dropped at the start of the span.

When I tried fix this I supposed it was the selection that got messed up and I wanted to use ReactEditor.findEventRange in the inputFromDrop branch of the beforeinput handler, but actually the InputEvent has no clientX/clientY, and therefore there is no way to know where the drop happened.

Since it looks that there is no way to make this work in every cases using beforeinput, my new changes do nothing in beforeinput handler when the inputType is deleteFromDrag or insertFromDrop, and enable back the handling in onDrop even if the browser HAS_BEFORE_INPUT_SUPPORT

**Comment by keyserfaty** [comment]
no updates on this? it's a pretty big issue.

**Comment by alexanderisora** [comment]
I'm waiting for this PR impatiently 😅

**Comment by clauderic** [comment]
Hey @llevequeblup, thanks for your contribution. I'm going to be closing this PR as we recently merged #4238, which was largely inspired by you PR and fixes the same issues.

**Pull request closed without merging**
