### PR TITLE
Fix NODE_TO_KEY correction for split_node and merge_node

### PR DESCRIPTION
**Pull request by bryanph**
**Description**
Fixes https://github.com/ianstormtaylor/slate/issues/4900

**Issue**
Fixes: https://github.com/ianstormtaylor/slate/issues/4900

**Example**
The logic in `with-react` was not resetting the node keys for the right nodes for `split_node` and `merge_node` operations. This fixes that so that on `split_node` the node being split does not get remounted and on `merge_node` the node being merged into also does not get remounted.

**Context**
See https://github.com/ianstormtaylor/slate/issues/4900

**Checks**
- [ ] The new code matches the existing patterns and styles.
- [ ] The tests pass with `yarn test`.
- [ ] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [ ] The relevant examples still work. (Run examples with `yarn start`.)
- [ ] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

### CODE REVIEW

**Review by dylans — COMMENTED** [review]
Thanks! I’d love to see a test for this though I know that’s not easy yet. Please add a changeset when you get a chance.

**Comment by bryanph** [comment]
@dylans yeah a test here would be nice indeed, will see what I can do

**Comment by nemanja-tosic** [comment]
@bryanph don't know about cypress, but here's a react test renderer version that fails against previous version but works with the PR:

```
it('should not unmount', async () => {
  const editor = withReact(createEditor())
  const value = [{ children: [{ text: 'hello' }] }]
  const mounts = jest.fn<void, [Element]>()

  let el: ReactTestRenderer

  act(() => {
    el = create(
      <Slate editor={editor} value={value} onChange={() => {}}>
        <DefaultEditable
          renderElement={({ element, children }) => {
            useEffect(() => mounts(element), [])

            return children
          }}
        />
      </Slate>,
      { createNodeMock }
    )
  })

  // slate updates at next tick, so we need this to be async
  await act(async () =>
    Transforms.splitNodes(editor, { at: { path: [0, 0], offset: 2 } })
  )

  expect(mounts).toHaveBeenCalledTimes(2)

  // TODO: assertion against something specific to elements
})
```

**Comment by bryanph** [comment]
@nemanja-tosic awesome, thanks! I pushed two tests for the particular cases being fixed here based on your example here. Let me know if there's something else I can assert here.

**Review by dylans — APPROVED** [review]

**Pull request merged**
