### PR TITLE
Try add Flow Annotation

### PR DESCRIPTION
**Pull request by joehua87**
I've try to add Flow Annotation as proposed in https://github.com/ianstormtaylor/slate/issues/83
I just worked with all the files in models & components/content & waiting for **feedbacks** before make it further
Please let me know if you need anything that make it works

Command:
```
npm run flow
```

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Hey @joehua87, this is awesome thank you for taking the time to do this!

I have one worry, which is that the methods right now are still not super-nailed down, since I'm still working on a few of the "core" requirements, so things may change a decent amount. For that reason, I'm thinking that we should keep this PR here but not merge it until things settle down a bit more.

I haven't used Flow before myself, so I'm not really sure what the workflow looks like, or what I'd be getting myself into by committing to maintain the flow annotations. What exactly would the commitment be?

**Comment by ctrlplusb** [comment]
This would be great. I'm a flow user, and have been creating definitions too. Happy to help out in any way when things have settled.

**Comment by joehua87** [comment]
@ianstormtaylor great to hear that. I will maintain this to keep it sync with the main repo. :)

**Comment by joehua87** [comment]
I think that we should make a separate type annotation in https://github.com/flowtype/flow-typed in order to not pollute the code

**Comment by frederickfogerty** [comment]
Hey @ctrlplusb, would you still have your definitions lying around by any chance? I'm trying to create some Typescript definitions, and having a flow version would make it a lot easier than creating the Typescript ones by scratch

**Pull request closed without merging**
