### PR TITLE
Node methods optimizations

### PR DESCRIPTION
**Pull request by Soreine**
Working on https://github.com/ianstormtaylor/slate/issues/180

I open this PR as a work in progress to gather reviews as I work on it.
I cannot measure the impact of the changes, so I'm not sure each point actually improves performances (tricky case of memoization).

So far:

- Optimize `Node.getParents` to return as soon as the child is found
- Add `Node.getAncestors` method (used in `Node.getClosest`)
- Optimize `Node.getClosest` to not use successive `getParent`, by using `Node.getAncestors` instead. I don't know if there is a benefit to this, since `getParent` is recursive and memoized.
- Remove extra use of `assertDescendant` (but keep throwing when not found) in the following implementations:
  - `Node.getPath`
  - `Node.updateDescendant`
  - `Node.removeDescendant`

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
@Soreine this is awesome!

Agreed that it's hard without a way to measure the impacts. Maybe there's a way we can get a benchmark-like test suite going so that we can know if we're making things more performant? I don't know much about benchmarking unfortunately.

**Comment by SamyPesse** [comment]
@ianstormtaylor Yes, we were talking with @Soreine today about making a PR to add benchmarks to Slate.
I think we can have a simple solution that prints the result and compare between versions using Travis build's logs.

We'll probably open another PR for the benchmarks. This PR still contains minors but required optimizations (ex: `X to return as soon as the child is found`, etc) that do not require benchmarks.

**Comment by Soreine** [comment]
@ianstormtaylor I think you can review/merge this PR. The changes are self-contained. There are still things to do, but I can always open a new PR.

**Comment by Soreine** [comment]
- Fixed `Node.findDescendant` which would not return nodes deeper than the first level.
- Implemented `Node.getFirstText` and `Node.getLastText` and used it where fit. I think even with memoization, these implementations still compete with a memoized call to `Node.getTexts`. It's still a constant complexity.

**Comment by Soreine** [comment]
Note to self: When we merge it, review if there are new places where we could use `node.getFirstText`

**Comment by ianstormtaylor** [comment]
Sweet, @Soreine if you can rebase against master I can get this merged!

**Comment by Soreine** [comment]
Done.

**Pull request merged**
