### PR TITLE
export SCHEMA to run normalize properly

### PR DESCRIPTION
**Pull request by sashless**
adressing https://github.com/ianstormtaylor/slate/issues/473

I took the easy way and just export it. 
A better solution might be to provide it magically to normalize ?

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Hey @sashless thanks for working on this! I think for now, instead of exporting it for public use, we can just require it by its path for the tests here. That way we don't need to commit to an extra export forever. Are you down to make that change?

**Comment by sashless** [comment]
yea i will push that later but the problem how to use normalize without the `SCHEMA` still persists in that case

**Comment by Soreine** [comment]
Having no way to normalize using the core schema is a problem for us too. Maybe the `normalize` transforms should default to using the core schema?

**Comment by Soreine** [comment]
I am using a workaround to normalize a whole document

```
// Normalize the document
const normalizedDocument = Slate.State.create({
        document
    }, { normalize: true })
    .document;

**Comment by ianstormtaylor** [comment]
What do you need to normalize with the core schema for? Just curious. 

I'm definitely down to default the normalize functions to use the core schema if you wanna PR! Thanks

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/675

**Pull request closed without merging**
