### PR TITLE
Fix long pressed accents on Chrome+macOS

### PR DESCRIPTION
**Pull request by Calyhre**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Fixing a bug

#### What's the new behavior?

On macOS, long press triggers an IME to insert an accent. Browsers that implements `beforeinput` event uses the `insertReplacementText` and a proper range. Chrome is instead selecting the character to replace, **right when the input is triggered**.

| **Before** | **After** |
| -- | -- |
|![][before]|![][after]|

[before]: https://user-images.githubusercontent.com/3692274/68779241-9b318000-0634-11ea-9c41-be9be33972e4.gif
[after]: https://user-images.githubusercontent.com/3692274/68779245-9cfb4380-0634-11ea-896f-83272a0a0763.gif

#### How does this change work?

If we detect macOS && Chrome, the we proceed to check if the DOM selection has been updated before the input event and a detection of a selection change. The check is very naive but enough for this particular case. This can't happen when previous editor selection was expanded I guess.

I had to expose through a query the composition state of the before plugin, this is used to discard completely this fix in case of a user using another IME.

This issue was also fixed by #3041 but the fix is more trustworthy in my opinion, as we are not relying on any previous input.

I couldn't figured out how to test this with the current toolchain.

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x] The relevant examples still work. (Run examples with `yarn watch`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #982 
Reviewers: @ianstormtaylor @knubie

### CODE REVIEW

**Comment by Calyhre** [comment]
⚠️ This does not work with composition 🙇‍♂️ Trying to find a better fix

**Comment by ianstormtaylor** [comment]
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.

**Comment by jens-lilt** [comment]
If I select the character in the menu with the arrow keys I can still reproduce this behavior in Slate 0.77.2
Typing the number under the letter works as expected

**Comment by BitPhinix** [comment]
Applying them using arrow keys indeed still does seem to cause issues on the latest version. If you raise an issue I'll take a look at it next week

**Pull request closed without merging**
