### PR TITLE
Fix mark removal at the edges of text nodes

### PR DESCRIPTION
**Pull request by erquhart**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Bugfix

#### What's the new behavior?
Toggling a mark off at the end of a text node and then continuing typing currently results in the mark becoming active again. This can also result in an empty editor with active marks, which can only be removed by selecting marked text and then toggling marks off.

This fix restores the original behavior.

#### How does this change work?

- Previously a set of marks could be passed to `insertTextByPath` for inclusion, but there was no way to ensure that _no_ marks were used, as an empty set was ignored. With this change, an empty set passed as the `marks` arg ensures that no marks are applied to the inserted text.
- `removeAllMarksByPath`, a currently unused and undocumented command, now has an extended signature to support the new behavior in `insertTextByPath`, optionally accepting an offset and text length so that marks can be removed at certain points within a node rather than from the entire node.
- `insertText`, as a higher level abstraction, will override this new behavior in `insertTextByPath` by giving preference to the marks collected from the selection, if any, as is this is the generally expected outcome as evidenced by Slate's tests.

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x] The relevant examples still work. (Run examples with `yarn watch`.)

#### Does this fix any issues or need any specific reviewers?

Fixes: #2736

### CODE REVIEW

**Comment by adjourn** [comment]
Found one failing scenario:

* select a word
* apply multiple marks
* drop collapsed selection in the middle of word
* if you disable one mark and type, same bug appears
* only works if you disable all active marks

**Comment by erquhart** [comment]
Good catch, adding a failing tests for that and taking a look now 👍

**Comment by erquhart** [comment]
Update: bug discovered by @adjourn revealed the real issue here - text insertion commands provide a way to _add_ marks, but no way to _remove_ them. Both his and my PR's attempted to re-interpret an empty set of marks to mean insert text with no marks, which works only because an empty set previously had no impact. But removing one of multiple marks can't be accomplished through the text insertion commands using the current API.

I'm spinning up the latest version of Slate that doesn't have this bug to determine how this used to work before Slate migrated away from leaves, hopefully that will shed some light on a path forward.

**Comment by adjourn** [comment]
@erquhart I managed to crack it, all test are passing. Do you mind if I borrow your commited tests?

**Comment by erquhart** [comment]
Go for it!

**Comment by adjourn** [comment]
@erquhart I managed to crack it, all test are passing. Do you mind if I borrow your commited tests?

I'm going to push latest working version in 15-30 minutes.

**Comment by erquhart** [comment]
Go for it!

**Comment by erquhart** [comment]
Pushing up some failing tests that I have locally as well.

**Comment by erquhart** [comment]
Closing in favor of #2818.

**Pull request closed without merging**
