### PR TITLE
Fix text not rerender by decorations change

### PR DESCRIPTION
**Pull request by ulion**
**Description**
like #4080 tried to fixed, the decorations change does not trigger Text node re-render (because of memo compare not consider decorations).
This PR fix it just straightforward, do lodash isEqual compare between decorations items.

After fix this, I found it still does not work, due to the other bug from Leaf memo, which compare leaf without compare the text field, but, with slate-collaborative as example, we use decorate to render remote caret, when user click the other place of same text but different position, the memo of Leaf does not re-render the updated Leaf (with text updated), because Text.matches does not compare text field, while the text prop transferred to Leaf is the common 'text value' before splitted by the caret (decorate) which does not change.

**Issue**
Fixes: #3751 #3447

**Example**
To make the remote caret (decorations) work, slate-collaborative have to update renderLeaf method each time when any decoration changes, which caused many unnecessary re-render. With this PR, only the updated (effected) text and leaf will be re-rendered.

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

### CODE REVIEW

**Comment by williamstein** [comment]
Big +1 to this PR.   I made similar (but much less efficient) fixes to my copy of react-slate, when implementing realtime collaboration as well.  In particular, I also implemented other user cursors using decorations and hit this issue.

**Comment by FezVrasta** [comment]
+1! We are using this fix with patch-package and it'd be great to have this merged.

**Comment by ianstormtaylor** [comment]
I believe this is solved by merging https://github.com/ianstormtaylor/slate/pull/3437/files but if that is not the case please feel free to comment and I can re-open. Thanks!

**Comment by HerbiePorter** [comment]
I think this may still be an issue @ianstormtaylor.  

In this example, I'm trying to decorate the selection on blur so that it still _appears_ selected but the decoration only applies to the leaf nodes on the next render (triggered by editing the editor content) even though the decorate function has run and been applied onBlur.  If this doesn't sound like the same issue I'm happy to open a new issue.

http://g.recordit.co/9zkYvOCN1G.gif

**Pull request closed without merging**
