### PR TITLE
set_node operations did not invert correctly after serialization

### PR DESCRIPTION
**Pull request by TheSpyder**
#### Is this adding or improving a _feature_ or fixing a _bug_?

Fixing a bug. Set node operations are not serializable as currently designed, which makes them difficult to use for collaboration.

When calling `Transforms.setNodes`, adding a property that doesn't already exist on the node sets the old value to undefined:

```
{
  type: 'set_node',
  path: [ 0 ],
  properties: { key: undefined },
  newProperties: { key: true }
}
```

This is not serializable (the `properties` object will be empty) resulting in an invalid operation when transmitted across a collaboration connection. This error does not manifest unless the operation is inverted on the other side of the connection (an uncommon but necessary requirement).

#### What's the new behavior?

With my change these operations use null:
```
{
  type: 'set_node',
  path: [ 0 ],
  properties: { key: null },
  newProperties: { key: true }
}
```

I have included two tests:
* After JSON stringify/parse, a `set_node` operation object is deep strict equal
* After JSON stringify/parse, a `set_node` operation can be used to invert the action it just performed

These are general properties every operation should be able to meet but I didn't want to add tests beyond the scope of this PR (however I could, we have similar tests in our collaboration codebase that verify this property).

#### How does this change work?

One line change. `properties[k] = node[k]` becomes `properties[k] = node[k] ?? null`.

#### Have you checked that...?

- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)

### CODE REVIEW

**Comment by TheSpyder** [comment]
As an alternative to this, applying a `set_node` operation could compare `properties` and `newProperties` to determine what to do (missing attributes in `newProperties` would be removed) instead of just relying on the new value being loosely equal to `null` to remove attributes:
https://github.com/ianstormtaylor/slate/blob/4e667b91099bdfadb7e2b15175055183be38dc4c/packages/slate/src/transforms/general.ts#L200-L204

**Comment by TheSpyder** [comment]
Sure, I can try that. I'm on leave until the end of next week but I'll give it a go soon.

**Comment by TheSpyder** [comment]
@ianstormtaylor that worked really well! I ended up omitting undefined properties completely, which I think is a better result all around.

**Comment by ianstormtaylor** [comment]
@TheSpyder nice, that's awesome! Thanks for taking the time to update it.

**Comment by TheSpyder** [comment]
I missed one code path in the changes I made to avoid `null` in `set_node`, and I didn't have time to start integrating this update with OT in my app until today so I only just hit the bug. Removing `set_node` null checks in my app now leads to nodes having attribute value `null`.

This is because `Transforms.unsetNodes` uses null values:
https://github.com/ianstormtaylor/slate/blob/737aaa9cde2d4a2d6d64b83256aa5d9d1b5ce720/packages/slate/src/transforms/node.ts#L802-L804

Which means that the way this code is now written, it needs to not add to `newProperties` when `props[k]` is null:
https://github.com/ianstormtaylor/slate/blob/737aaa9cde2d4a2d6d64b83256aa5d9d1b5ce720/packages/slate/src/transforms/node.ts#L637-L641

I'll work on a new PR tomorrow.

**Comment by TheSpyder** [comment]
I actually implemented most of the change that same day, but then forgot about it for 3 months. Oops. PR #4428 now open.

**Pull request merged**
