### PR TITLE
Fix toolbar and mentions examples on android

### PR DESCRIPTION
**Pull request by BitPhinix**
**Description**
Updates the mention and hovering toolbar example so that they properly work on android.

This PR also contains a potentially breaking change: It memos the Editable component to make it easier to work with on android since renders cause a flush which will mess with the IME input.

I'm aware that there is still an issue when using swiftkey in the mention example. Swiftkey will duplicate the text inside the mention when pressing space directly after a mention component. This is (one of many) bugs with swiftkey itself and I haven't yet found a way to prevent it (also happens in a non-slate contenteditable, and every other editor out there that is based upon it)

**Checks**
- [x] The new code matches the existing patterns and styles.
- [x] The tests pass with `yarn test`.
- [x] The linter passes with `yarn lint`. (Fix errors with `yarn fix`.)
- [x] The relevant examples still work. (Run examples with `yarn start`.)
- [x] You've [added a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) if changing functionality. (Add one with `yarn changeset add`.)

### CODE REVIEW

**Comment by BitPhinix** [comment]
@dylans, I've "refactored" the pending diff handling a bit; it should now be nicer to work with. Not a perfect implementation currently, but I'll clean it up if you like the approach here. We could use the same API for desktop composition, although another rabbit hole I haven't looked into yet.

**Comment by bryanph** [comment]
@BitPhinix could you explain a little how the `shouldFlushPendingChanges` works and how it should be modified to make android work in different use cases? 🙏

**Comment by BitPhinix** [comment]
Sure, there are mainly two use-cases for it:

1. Cancel composition to perform some action on the pending editor state while the user is composing (mainly relevant for auto-replace shortcuts like the markdown shortcut example)
2. Update some component/state to reflect the pending state while the user is composing (like in the mention example)

It's invoked with a "save" timing after each composition change, so you could modify the editor state inside it without interfering too much with the IME (I say too much because it still will if the render takes long/you type very fast). Forcing a flush manually by returning true will have these issues as well, so you should use it very sparingly and only where you have no other choice (like with markdown shortcuts).

We never had an API to deal with/update the editor state while the user is composing since the use-case is rare on desktop. We currently just insert the text on composition end. It's needed on android because composition is very long-lived (you can write an entire paragraph on android inside a single composition session).

**Comment by BitPhinix** [comment]
Any objections/comments on this, or should I create a polished version of this PR?

**Comment by dylans** [comment]
> Any objections/comments on this, or should I create a polished version of this PR?

My instinct is that I wish this didn't feel so complex, but I don't have a better suggestion. Let's go for the polished PR. Thanks!

**Comment by piscessss** [comment]
I had the same problem.When will the content of this branch be officially released?Thanks.

**Comment by Sunshine168** [comment]
Any update?

**Comment by dylans** [comment]
We've had a few smaller PRs to fix parts of this. Closing in favor of a hopefully smaller PR later to address any remaining issues.

**Pull request closed without merging**
