### PR TITLE
fix(firefox): fixed the bug that happens when changing the focus from one field to another

### PR DESCRIPTION
**Pull request by lakatosandrei**
#### Is this adding or improving a _feature_ or fixing a _bug_?

fixing

This bug:
https://drive.google.com/file/d/1uG3kKuGRLO8d-XHAlDH4cz9dkgbuvPvM/view

There's a problem with the `updateSelection` function for Firefox. When changing focus from one editor to another the previous element is focused again.

#### What's the new behavior?

When trying to change the focus from one slate editor to another slate editor the cursor is placed in the new editor where it should.

This is the new behaviour:
http://www.giphy.com/gifs/LVuGFQ0qlmKb7HBcLg

#### How does this change work?

I removed the code that was not needed anymore and added a check for some code that was messing up things on Firefox. Previously some of the code was designed specifically for Firefox.

#### Have you checked that...?

* [x] The new code matches the existing patterns and styles.
* [x] The tests pass with `yarn test`.
* [x] The linter passes with `yarn lint`. (Fix errors with `yarn prettier`.)
* [x] The relevant examples still work. (Run examples with `yarn watch`.)

#### Does this fix any issues or need any specific reviewers?

Don't think so

### CODE REVIEW

**Comment by CameronAckermanSEL** [comment]
@lakatosandrei Hiya, would you mind clearing out this last eslint warning? I think that's the only barrier to getting this looked at.

Thanks :)

**Comment by ererik** [comment]
At first glance, this seems to solve #2631 and #2095 .

**Comment by CameronAckermanSEL** [comment]
This looks good to me, can we revert the updates to the package.json files?

**Comment by lakatosandrei** [comment]
> This looks good to me, can we revert the updates to the package.json files?

Done

**Comment by lakatosandrei** [comment]
Fixed the conflicts as well.

**Comment by darkyshiny** [comment]
@ianstormtaylor Could you take a look at this so that it can hopefully be merged soon?

This fixes #2095 which has been around for a long time and is a pretty bad experience for firefox users

**Comment by kaydelaney** [comment]
Us at Grafana would also love to see this in the next release - Slate is becoming an increasingly important part of Grafana, and I'm sure we'd be willing to share some maintenance responsibilities to see PRs like this one move along more smoothly.

@ianstormtaylor Any thoughts on having this PR merged sometime soon? (After conflicts are resolved, of course). Thanks!

**Comment by ianstormtaylor** [comment]
Thanks @lakatosandrei!

**Comment by lakatosandrei** [comment]
> Thanks @lakatosandrei!

My pleasure!

**Comment by themithy** [comment]
Hi,

I looks like this commit causes a regression on firefox, you can see it on one of the examples on the home page.

1. Pressing arrow left or right does not move the selection.
2. Typing a character makes the selection to jump somewhere else in the editor.

This makes the experience pretty difficult.

Firefox 68.

Cheers.

**Comment by clauderic** [comment]
I can confirm the issue @themithy is seeing, both with Firefox 66 and 68 (latest). The left and right arrows do not work to move the cursor. 

Typing initially inserts the first character in the right position, but then the cursor jumps to the nearest mark or the beginning of the current block if there are no marks in the current block.

This PR should probably be reverted, and the issue it aimed to solve should be fixed in a subsequent PR seeing as it causes a much larger issue which makes Slate unusable on Firefox

**Comment by kaydelaney** [comment]
As for the issue itself, I spent some time looking into it today and it seems like the root cause is that on Firefox at least, `componentDidUpdate`, and consequently `updateSelection` is called before `onNativeSelectionChange`, but _after_ the native selection is actually updated, causing all ranges to be removed from the native selection.

**Pull request merged**
